from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HTML = ROOT / "playable" / "midnight_bloom_prototype.html"
BOARD_SIZE = 8
SHAPE_VALUE = 2
BASE_VALUES = [0, 1, 3, 4, 5]


def make_board(shape_cells):
    board = [
        [BASE_VALUES[(x + y * 2) % len(BASE_VALUES)] for x in range(BOARD_SIZE)]
        for y in range(BOARD_SIZE)
    ]
    for x, y in shape_cells:
        board[y][x] = SHAPE_VALUE
    return board


def find_run_segments(board):
    segments = []
    for y in range(BOARD_SIZE):
        start = 0
        for x in range(1, BOARD_SIZE + 1):
            if x == BOARD_SIZE or board[y][x] != board[y][start]:
                if board[y][start] is not None and x - start >= 3:
                    segments.append({
                        "val": board[y][start],
                        "direction": "horizontal",
                        "cells": [(mx, y) for mx in range(start, x)],
                    })
                start = x

    for x in range(BOARD_SIZE):
        start = 0
        for y in range(1, BOARD_SIZE + 1):
            if y == BOARD_SIZE or board[y][x] != board[start][x]:
                if board[start][x] is not None and y - start >= 3:
                    segments.append({
                        "val": board[start][x],
                        "direction": "vertical",
                        "cells": [(x, my) for my in range(start, y)],
                    })
                start = y
    return segments


def matches(board):
    segments = find_run_segments(board)
    parents = list(range(len(segments)))

    def find(index):
        if parents[index] != index:
            parents[index] = find(parents[index])
        return parents[index]

    def union(a, b):
        root_a = find(a)
        root_b = find(b)
        if root_a != root_b:
            parents[root_b] = root_a

    owners_by_cell = {}
    for index, segment in enumerate(segments):
        for cell in segment["cells"]:
            owners = owners_by_cell.setdefault(cell, [])
            for owner in owners:
                union(index, owner)
            owners.append(index)

    groups = {}
    for index, segment in enumerate(segments):
        root = find(index)
        group = groups.setdefault(root, {
            "val": segment["val"],
            "cells": set(),
            "runs": [],
        })
        group["cells"].update(segment["cells"])
        group["runs"].append(segment)

    found = []
    for group in groups.values():
        cells = sorted(group["cells"], key=lambda cell: (cell[1], cell[0]))
        found.append({
            "val": group["val"],
            "cells": cells,
            "len": len(cells),
            "runs": group["runs"],
            "shape": classify_shape(cells, group["runs"]),
        })
    return sorted(found, key=lambda match: match["len"], reverse=True)


def classify_shape(cells, runs):
    horizontal = [run for run in runs if run["direction"] == "horizontal"]
    vertical = [run for run in runs if run["direction"] == "vertical"]
    if not horizontal or not vertical:
        return "line"

    cell_set = set(cells)
    intersections = []
    for h_run in horizontal:
        h_cells = set(h_run["cells"])
        for v_run in vertical:
            intersections.extend(cell for cell in v_run["cells"] if cell in h_cells)

    best_arms = 0
    for x, y in intersections:
        arms = sum((
            (x - 1, y) in cell_set,
            (x + 1, y) in cell_set,
            (x, y - 1) in cell_set,
            (x, y + 1) in cell_set,
        ))
        best_arms = max(best_arms, arms)

    if best_arms >= 4:
        return "cross"
    if best_arms == 3:
        return "t"
    return "l"


def assert_single_shape(name, cells, expected_kind):
    found = matches(make_board(cells))
    if len(found) != 1:
        raise SystemExit(f"{name}: expected 1 match, found {len(found)}: {found}")
    match = found[0]
    expected_cells = sorted(cells, key=lambda cell: (cell[1], cell[0]))
    if match["cells"] != expected_cells:
        raise SystemExit(f"{name}: cleared {match['cells']} instead of {expected_cells}")
    if match["shape"] != expected_kind:
        raise SystemExit(f"{name}: classified as {match['shape']} instead of {expected_kind}")


def assert_no_match(name, cells):
    found = matches(make_board(cells))
    if found:
        raise SystemExit(f"{name}: expected no match, found {found}")


def verify_source_hooks():
    html = HTML.read_text()
    required = [
        "function analyzeMatchShape",
        "shapeAuditData",
        "function analyzeBoardSnapshot",
        "Prototype match-shape review hook",
        "Witch's Cross!",
        "Night Garden L-Bloom!",
        "Twin Stem Bloom!",
        "function demoMatchShape",
        "const maxCascades",
        "resolveAnimated({ maxCascades: 1 })",
        "const roundTemplates",
        "function maybeCompleteRound",
        "function demoCompleteBouquet",
        "demoCompleteBtn",
        "Complete Bouquet",
        "round-one-active",
        "body.round-one-active:not(.first-move-made) #shuffleBtn",
        "firstSwapCue",
        "Swap the glowing pair",
        "swap-path-arrow",
        "function renderFirstSwapArrow(boardEl)",
        "renderFirstSwapArrow(boardEl);",
        "swap-arrow-pulse",
        "round-one-black-candle-cue",
        "Make 4 Bone Stars - Black Candle Vine burns a row.",
        "round-one-followup-cue",
        "Keep matching - swap the glowing pair.",
        "round-one-refused",
        "Swap the glowing pair to open the next harvest.",
        "first-swap-cue::before",
        "GLYPH GUIDE",
        "BLACK CANDLE",
        "moves-counter",
        "body.round-one-active .objective-target",
        "function firstSwapCueText(a, b)",
        "Crack the marked thorns",
        "thorn-lesson-active",
        "function focusedRoundTwoHarvestSummary(result)",
        "isRestoredNextOrderFocus() || (bouquetStreak < 1",
        "round-two-followup-cue",
        "NEXT BLOOM",
        "${flowers[remainingTarget.flowerId][0]} next ${direction}",
        "const hintDelay = currentRound === 1 ? 350 : isRestoredNextOrderFocus() ? 650 : 7000;",
        "swap-snap",
        "activeSwapCells",
        "<strong>First bloom!</strong> Your bouquet is already taking shape.",
        "Keep the authored opening three-match from randomly extending",
        "board[originY][originX + 3] = fillerB;",
        "board[originY + 2][originX + 1] = fillerD;",
        "board[originY][originX - 1] = fillerC;",
        "const authoredRoundOneLesson = currentRound === 1",
        "{ maxCascades: 1, quietReseed: true }",
        "function finishResolve(result, options = {})",
        "function launchObjectiveFlights(gained, gainedCells = [])",
        "gainedCells: flowers.map(() => [])",
        "pulseOrderCounts(result.gained, result.gainedCells)",
        "const originX = boardRect.left + ((origin[0] + 0.5) / BOARD_SIZE) * boardRect.width;",
        "objective-flight",
        "objective-target.order-pulse::after",
        "objective-sip",
        "flight.src = flowers[target.flowerId][1]",
        "No bloom — follow the glowing pair.",
        "const focusedCueActive = (currentRound === 1 || isRestoredNextOrderFocus())",
        "swap-refused",
        "function restoreFirstSwapCueAfterRefusal",
        "restoreFirstSwapCueAfterRefusal();",
        "isRestoredNextOrderFocus() && hasMadeValidMove && target",
        "function shouldPreserveSelectedHintPair",
        "const selectedHintPair = new Set(idleHintCells);",
        "idleHintCells = selectedHintPair;",
        "function finishTileSwipe(event, x, y)",
        "SWIPE_THRESHOLD",
        "tile.setPointerCapture(event.pointerId)",
        "function pulseHaptic(pattern)",
        "pulseHaptic(18)",
        "pulseHaptic([10, 35, 18])",
        "let bloomAudioContext = null",
        "function bloomAudioCtx()",
        "function playBloomTone(frequency, startOffset, duration",
        "function playBloomSound(kind, detail = {})",
        "playBloomSound(\"invalid\")",
        "playBloomSound(\"match\", { cascade: cascadeIndex, lineRelic: wave.lineRelics.length > 0 })",
        "playBloomSound(\"complete\")",
        "playBloomSound(\"restore\")",
        "data-flower-id",
        "roundOneRestoration",
        "coin-payoff",
        "coin-payoff-flight",
        "id=\"coinPayoff\"",
        "greenhouse-awakening",
        "body.round-one-active.round-one-complete .ritual-log { display:none; }",
        "let coins = 0",
        "const streakPayout = plan.round === 1",
        "First Bouquet Sealed · +120 coin reward",
        "Greenhouse Restored ·",
        "restoration-ledger",
        "restoration-xp-preview",
        "function restorationGreenhouseXpPreview",
        "Greenhouse +180 XP",
        "greenhouse-payoff-fill",
        "Next Order: Moonlit Wreath is ready.",
        "Restore Greenhouse · 100 coins",
        "function restoreRoundOneGreenhouse",
        "nextOrderBtn",
        "Next Order →",
        "roundOneRestored",
        "next-order-cue",
        "Restored Greenhouse - Moonlit Wreath begins",
        "restored-greenhouse-handoff",
        "restored-next-order-focus",
        "restored-greenhouse-status",
        "function renderRestoredGreenhouseStatus",
        "Glass relit · Greenhouse",
        "function isRestoredNextOrderFocus",
        "return currentRound === 2 && roundOneRestored && !roundComplete;",
        "body.restored-next-order-focus .controls",
        "body.restored-next-order-focus:not(.restored-greenhouse-handoff):not(.first-move-made) .first-swap-cue",
        "isRestoredNextOrderFocus() ? 650 : 7000",
        "body.restored-greenhouse-handoff .controls",
        "function startRestoredGreenhouseHandoff",
        "function focusRestoredNextOrderViewport",
        "window.scrollTo({ top: 0, behavior: \"auto\" })",
        "<strong>Restored Greenhouse:</strong> Round ${plan.round}: ${plan.name} begins in the relit glass.",
        "Bouquet Streak",
        "bouquetStreak",
        "bouquetStreakBadge",
        "nextStreakTargetBadge",
        "Next Streak Target",
        "function nextStreakTargetMarkup",
        "STREAK_COIN_BONUS_STEP",
        "STREAK_COIN_BONUS_CAP",
        "function bouquetStreakBonusPercent",
        "function bouquetStreakPayout",
        "function validBouquetStreak",
        "Choose Your Reward",
        "rewardChoicePanel",
        "rewardChoiceState",
        "reward-choice-value",
        "reward-choice-claim",
        "Greenhouse Cuttings",
        "Apothecary Kit",
        "Black Market Favor",
        "function choosePostBouquetReward",
        "function applyDefaultRewardChoice",
        "function validRewardChoiceState",
        "data-reward-choice=\"greenhouse\"",
        "data-reward-choice=\"apothecary\"",
        "data-reward-choice=\"blackMarket\"",
        "Flowerpedia",
        "Flowerpedia unlocked",
        "flowerpediaEntries",
        "flowerpediaLedger",
        "flowerpediaModal",
        "flowerpediaUnlocked",
        "flowerpediaUnlocks",
        "Velvet Funeral",
        "Cursed Thorn Field Note",
        "function unlockFlowerpediaEntry",
        "function renderFlowerpediaLedger",
        "function renderFlowerpediaEntries",
        "function validFlowerpediaUnlocks",
        "FLOWERPEDIA_FIRST_BOUQUET_ID",
        "FLOWERPEDIA_THORN_NOTE_ID",
        "Chapter 1: Midnight Conservatory",
        "Glasshouse Atrium",
        "chapterProgress",
        "chapterOneProgress",
        "chapterRewardsClaimed",
        "chapterRewards",
        "Chapter 1 reward claimed",
        "function maybeClaimChapterOneReward",
        "function renderChapterOneProgress",
        "function chapterOneModalMarkup",
        "function validChapterRewardsClaimed",
        "CHAPTER_ONE_REWARD_ID",
        "The Bouquet Withered",
        "Retry Bouquet",
        "failedBouquetGoals",
        "retryBouquetPrompt",
        "function isBouquetFailed",
        "function failedBouquetCopy",
        "function failedBouquetRitualMessage",
        "function markBouquetFailed",
        "function remainingObjectiveRows",
        "function roundObjectivesComplete",
        "Bouquet Path",
        "bouquetPath",
        "bouquet-path-nodes",
        "data-bouquet-state=\"complete\"",
        "data-bouquet-state=\"current\"",
        "data-bouquet-state=\"locked\"",
        "data-bouquet-state=\"withered\"",
        "function renderBouquetPath",
        "function bouquetPathRoundNumbers",
        "function bouquetPathNodeMarkup",
        "function bouquetPathState",
        "pathLedgerDrawer",
        "Path / Ledger",
        "Future rewards hidden",
        "Round 3 Focus",
        "roundThreeFocus",
        "Bloodroot Compact payoff",
        "data-round-three-state=\"tease\"",
        "data-round-three-state=\"next\"",
        "data-round-three-state=\"current\"",
        "data-round-three-state=\"withered\"",
        "data-round-three-state=\"complete\"",
        "function renderRoundThreeFocus",
        "function roundThreeFocusState",
        "function roundThreeFocusCopy",
        "function roundThreePayoffCopy",
        "Round 4 Contract",
        "roundFourPreview",
        "Saint's Night Ledger payoff",
        "Sol Rot Seal",
        "data-round-four-state=\"tease\"",
        "data-round-four-state=\"next\"",
        "data-round-four-state=\"current\"",
        "data-round-four-state=\"withered\"",
        "data-round-four-state=\"complete\"",
        "function renderRoundFourPreview",
        "function roundFourPreviewState",
        "function roundFourPreviewCopy",
        "function roundFourPayoffCopy",
        "Round 5 Grand Bouquet",
        "roundFivePreview",
        "Sub Rosa Grand Bouquet payoff",
        "Sub Rosa Grand Cache",
        "data-round-five-state=\"tease\"",
        "data-round-five-state=\"next\"",
        "data-round-five-state=\"current\"",
        "data-round-five-state=\"withered\"",
        "data-round-five-state=\"complete\"",
        "function renderRoundFivePreview",
        "function roundFivePreviewState",
        "function roundFivePreviewCopy",
        "function roundFivePayoffCopy",
        "Round 6 Encore Loop",
        "roundSixPreview",
        "First Bouquet 2",
        "Round 6 encore payoff",
        "data-round-six-state=\"tease\"",
        "data-round-six-state=\"next\"",
        "data-round-six-state=\"current\"",
        "data-round-six-state=\"withered\"",
        "data-round-six-state=\"complete\"",
        "function renderRoundSixPreview",
        "function roundSixPreviewState",
        "function roundSixPreviewCopy",
        "function roundSixPayoffCopy",
        "Round 7 Thorn Encore",
        "roundSevenPreview",
        "Moonlit Wreath 2",
        "Round 7 encore Cursed Thorn payoff",
        "data-round-seven-state=\"tease\"",
        "data-round-seven-state=\"next\"",
        "data-round-seven-state=\"current\"",
        "data-round-seven-state=\"withered\"",
        "data-round-seven-state=\"complete\"",
        "function renderRoundSevenPreview",
        "function roundSevenPreviewState",
        "function roundSevenPreviewCopy",
        "function roundSevenPayoffCopy",
        "Round 8 Bloodroot Encore",
        "roundEightPreview",
        "Bloodroot Compact 2",
        "Round 8 encore Bloodroot Compact payoff",
        "data-round-eight-state=\"tease\"",
        "data-round-eight-state=\"next\"",
        "data-round-eight-state=\"current\"",
        "data-round-eight-state=\"withered\"",
        "data-round-eight-state=\"complete\"",
        "function renderRoundEightPreview",
        "function roundEightPreviewState",
        "function roundEightPreviewCopy",
        "function roundEightPayoffCopy",
        "Round 9 Ledger Encore",
        "roundNinePreview",
        "Saint's Night Ledger 2",
        "Round 9 encore Saint's Night Ledger payoff",
        "data-round-nine-state=\"tease\"",
        "data-round-nine-state=\"next\"",
        "data-round-nine-state=\"current\"",
        "data-round-nine-state=\"withered\"",
        "data-round-nine-state=\"complete\"",
        "function renderRoundNinePreview",
        "function roundNinePreviewState",
        "function roundNinePreviewCopy",
        "function roundNinePayoffCopy",
        "Round 10 Grand Encore",
        "roundTenPreview",
        "Sub Rosa Grand Bouquet 2",
        "Round 10 encore Sub Rosa Grand Bouquet payoff",
        "data-round-ten-state=\"tease\"",
        "data-round-ten-state=\"next\"",
        "data-round-ten-state=\"current\"",
        "data-round-ten-state=\"withered\"",
        "data-round-ten-state=\"complete\"",
        "function renderRoundTenPreview",
        "function roundTenPreviewState",
        "function roundTenPreviewCopy",
        "function roundTenPayoffCopy",
        "Round 11 First Bouquet Encore",
        "roundElevenPreview",
        "First Bouquet 3",
        "Round 11 encore First Bouquet payoff",
        "data-round-eleven-state=\"tease\"",
        "data-round-eleven-state=\"next\"",
        "data-round-eleven-state=\"current\"",
        "data-round-eleven-state=\"withered\"",
        "data-round-eleven-state=\"complete\"",
        "function renderRoundElevenPreview",
        "function roundElevenPreviewState",
        "function roundElevenPreviewCopy",
        "function roundElevenPayoffCopy",
        "Round 12 Moonlit Wreath Encore",
        "roundTwelvePreview",
        "Moonlit Wreath 3",
        "Round 12 encore Moonlit Wreath payoff",
        "data-round-twelve-state=\"tease\"",
        "data-round-twelve-state=\"next\"",
        "data-round-twelve-state=\"current\"",
        "data-round-twelve-state=\"withered\"",
        "data-round-twelve-state=\"complete\"",
        "function renderRoundTwelvePreview",
        "function roundTwelvePreviewState",
        "function roundTwelvePreviewCopy",
        "function roundTwelvePayoffCopy",
        "Round 13 Bloodroot Compact Encore",
        "roundThirteenPreview",
        "Bloodroot Compact 3",
        "Round 13 encore Bloodroot Compact payoff",
        "data-round-thirteen-state=\"tease\"",
        "data-round-thirteen-state=\"next\"",
        "data-round-thirteen-state=\"current\"",
        "data-round-thirteen-state=\"withered\"",
        "data-round-thirteen-state=\"complete\"",
        "function renderRoundThirteenPreview",
        "function roundThirteenPreviewState",
        "function roundThirteenPreviewCopy",
        "function roundThirteenPayoffCopy",
        "Round 14 Saint's Night Ledger Encore",
        "roundFourteenPreview",
        "Saint's Night Ledger 3",
        "Round 14 encore Saint's Night Ledger payoff",
        "data-round-fourteen-state=\"tease\"",
        "data-round-fourteen-state=\"next\"",
        "data-round-fourteen-state=\"current\"",
        "data-round-fourteen-state=\"withered\"",
        "data-round-fourteen-state=\"complete\"",
        "function renderRoundFourteenPreview",
        "function roundFourteenPreviewState",
        "function roundFourteenPreviewCopy",
        "function roundFourteenPayoffCopy",
        "Round 15 Sub Rosa Grand Bouquet Encore",
        "roundFifteenPreview",
        "Sub Rosa Grand Bouquet 3",
        "Round 15 encore Sub Rosa Grand Bouquet payoff",
        "data-round-fifteen-state=\"tease\"",
        "data-round-fifteen-state=\"next\"",
        "data-round-fifteen-state=\"current\"",
        "data-round-fifteen-state=\"withered\"",
        "data-round-fifteen-state=\"complete\"",
        "function renderRoundFifteenPreview",
        "function roundFifteenPreviewState",
        "function roundFifteenPreviewCopy",
        "function roundFifteenPayoffCopy",
        "Round 16 First Bouquet Encore",
        "roundSixteenPreview",
        "First Bouquet 4",
        "Round 16 encore First Bouquet payoff",
        "data-round-sixteen-state=\"tease\"",
        "data-round-sixteen-state=\"next\"",
        "data-round-sixteen-state=\"current\"",
        "data-round-sixteen-state=\"withered\"",
        "data-round-sixteen-state=\"complete\"",
        "function renderRoundSixteenPreview",
        "function roundSixteenPreviewState",
        "function roundSixteenPreviewCopy",
        "function roundSixteenPayoffCopy",
        "Round 17 Moonlit Wreath Encore",
        "roundSeventeenPreview",
        "Moonlit Wreath 4",
        "Round 17 encore Moonlit Wreath payoff",
        "data-round-seventeen-state=\"tease\"",
        "data-round-seventeen-state=\"next\"",
        "data-round-seventeen-state=\"current\"",
        "data-round-seventeen-state=\"withered\"",
        "data-round-seventeen-state=\"complete\"",
        "function renderRoundSeventeenPreview",
        "function roundSeventeenPreviewState",
        "function roundSeventeenPreviewCopy",
        "function roundSeventeenPayoffCopy",
        "Round 18 Bloodroot Compact Encore",
        "roundEighteenPreview",
        "Bloodroot Compact 4",
        "Round 18 encore Bloodroot Compact payoff",
        "data-round-eighteen-state=\"tease\"",
        "data-round-eighteen-state=\"next\"",
        "data-round-eighteen-state=\"current\"",
        "data-round-eighteen-state=\"withered\"",
        "data-round-eighteen-state=\"complete\"",
        "function renderRoundEighteenPreview",
        "function roundEighteenPreviewState",
        "function roundEighteenPreviewCopy",
        "function roundEighteenPayoffCopy",
        "Round 19 Saint's Night Ledger Encore",
        "roundNineteenPreview",
        "Saint's Night Ledger 4",
        "Round 19 encore Saint's Night Ledger payoff",
        "data-round-nineteen-state=\"tease\"",
        "data-round-nineteen-state=\"next\"",
        "data-round-nineteen-state=\"current\"",
        "data-round-nineteen-state=\"withered\"",
        "data-round-nineteen-state=\"complete\"",
        "function renderRoundNineteenPreview",
        "function roundNineteenPreviewState",
        "function roundNineteenPreviewCopy",
        "function roundNineteenPayoffCopy",
        "Round 20 Sub Rosa Grand Bouquet Encore",
        "roundTwentyPreview",
        "Sub Rosa Grand Bouquet 4",
        "Round 20 encore Sub Rosa Grand Bouquet payoff",
        "data-round-twenty-state=\"tease\"",
        "data-round-twenty-state=\"next\"",
        "data-round-twenty-state=\"current\"",
        "data-round-twenty-state=\"withered\"",
        "data-round-twenty-state=\"complete\"",
        "function renderRoundTwentyPreview",
        "function roundTwentyPreviewState",
        "function roundTwentyPreviewCopy",
        "function roundTwentyPayoffCopy",
        "Round 21 First Bouquet Encore",
        "roundTwentyOnePreview",
        "First Bouquet 5",
        "Round 21 encore First Bouquet payoff",
        "data-round-twenty-one-state=\"tease\"",
        "data-round-twenty-one-state=\"next\"",
        "data-round-twenty-one-state=\"current\"",
        "data-round-twenty-one-state=\"withered\"",
        "data-round-twenty-one-state=\"complete\"",
        "function renderRoundTwentyOnePreview",
        "function roundTwentyOnePreviewState",
        "function roundTwentyOnePreviewCopy",
        "function roundTwentyOnePayoffCopy",
        "Round 22 Moonlit Wreath Encore",
        "roundTwentyTwoPreview",
        "Moonlit Wreath 5",
        "Round 22 encore Moonlit Wreath payoff",
        "data-round-twenty-two-state=\"tease\"",
        "data-round-twenty-two-state=\"next\"",
        "data-round-twenty-two-state=\"current\"",
        "data-round-twenty-two-state=\"withered\"",
        "data-round-twenty-two-state=\"complete\"",
        "function renderRoundTwentyTwoPreview",
        "function roundTwentyTwoPreviewState",
        "function roundTwentyTwoPreviewCopy",
        "function roundTwentyTwoPayoffCopy",
        "Round 23 Bloodroot Compact Encore",
        "roundTwentyThreePreview",
        "Bloodroot Compact 5",
        "Round 23 encore Bloodroot Compact payoff",
        "data-round-twenty-three-state=\"tease\"",
        "data-round-twenty-three-state=\"next\"",
        "data-round-twenty-three-state=\"current\"",
        "data-round-twenty-three-state=\"withered\"",
        "data-round-twenty-three-state=\"complete\"",
        "function renderRoundTwentyThreePreview",
        "function roundTwentyThreePreviewState",
        "function roundTwentyThreePreviewCopy",
        "function roundTwentyThreePayoffCopy",
        "Round 24 Saint's Night Ledger Encore",
        "roundTwentyFourPreview",
        "Saint's Night Ledger 5",
        "Round 24 encore Saint's Night Ledger payoff",
        "data-round-twenty-four-state=\"tease\"",
        "data-round-twenty-four-state=\"next\"",
        "data-round-twenty-four-state=\"current\"",
        "data-round-twenty-four-state=\"withered\"",
        "data-round-twenty-four-state=\"complete\"",
        "function renderRoundTwentyFourPreview",
        "function roundTwentyFourPreviewState",
        "function roundTwentyFourPreviewCopy",
        "function roundTwentyFourPayoffCopy",
        "Round 25 Sub Rosa Grand Bouquet Encore",
        "roundTwentyFivePreview",
        "Sub Rosa Grand Bouquet 5",
        "Round 25 encore Sub Rosa Grand Bouquet payoff",
        "data-round-twenty-five-state=\"tease\"",
        "data-round-twenty-five-state=\"next\"",
        "data-round-twenty-five-state=\"current\"",
        "data-round-twenty-five-state=\"withered\"",
        "data-round-twenty-five-state=\"complete\"",
        "function renderRoundTwentyFivePreview",
        "function roundTwentyFivePreviewState",
        "function roundTwentyFivePreviewCopy",
        "function roundTwentyFivePayoffCopy",
        "Round 26 First Bouquet Encore",
        "roundTwentySixPreview",
        "First Bouquet 6",
        "Round 26 encore First Bouquet payoff",
        "data-round-twenty-six-state=\"tease\"",
        "data-round-twenty-six-state=\"next\"",
        "data-round-twenty-six-state=\"current\"",
        "data-round-twenty-six-state=\"withered\"",
        "data-round-twenty-six-state=\"complete\"",
        "function renderRoundTwentySixPreview",
        "function roundTwentySixPreviewState",
        "function roundTwentySixPreviewCopy",
        "function roundTwentySixPayoffCopy",
        "Round 27 Moonlit Wreath Encore",
        "roundTwentySevenPreview",
        "Moonlit Wreath 6",
        "Round 27 encore Moonlit Wreath payoff",
        "data-round-twenty-seven-state=\"tease\"",
        "data-round-twenty-seven-state=\"next\"",
        "data-round-twenty-seven-state=\"current\"",
        "data-round-twenty-seven-state=\"withered\"",
        "data-round-twenty-seven-state=\"complete\"",
        "function renderRoundTwentySevenPreview",
        "function roundTwentySevenPreviewState",
        "function roundTwentySevenPreviewCopy",
        "function roundTwentySevenPayoffCopy",
        "Round 28 Bloodroot Compact Encore",
        "roundTwentyEightPreview",
        "Bloodroot Compact 6",
        "Round 28 encore Bloodroot Compact payoff",
        "data-round-twenty-eight-state=\"tease\"",
        "data-round-twenty-eight-state=\"next\"",
        "data-round-twenty-eight-state=\"current\"",
        "data-round-twenty-eight-state=\"withered\"",
        "data-round-twenty-eight-state=\"complete\"",
        "function renderRoundTwentyEightPreview",
        "function roundTwentyEightPreviewState",
        "function roundTwentyEightPreviewCopy",
        "function roundTwentyEightPayoffCopy",
        "Round 29 Saint's Night Ledger Encore",
        "roundTwentyNinePreview",
        "Saint's Night Ledger 6",
        "Round 29 encore Saint's Night Ledger payoff",
        "data-round-twenty-nine-state=\"tease\"",
        "data-round-twenty-nine-state=\"next\"",
        "data-round-twenty-nine-state=\"current\"",
        "data-round-twenty-nine-state=\"withered\"",
        "data-round-twenty-nine-state=\"complete\"",
        "function renderRoundTwentyNinePreview",
        "function roundTwentyNinePreviewState",
        "function roundTwentyNinePreviewCopy",
        "function roundTwentyNinePayoffCopy",
        "Round 30 Sub Rosa Grand Bouquet Encore",
        "roundThirtyPreview",
        "Sub Rosa Grand Bouquet 6",
        "Round 30 encore Sub Rosa Grand Bouquet payoff",
        "data-round-thirty-state=\"tease\"",
        "data-round-thirty-state=\"next\"",
        "data-round-thirty-state=\"current\"",
        "data-round-thirty-state=\"withered\"",
        "data-round-thirty-state=\"complete\"",
        "function renderRoundThirtyPreview",
        "function roundThirtyPreviewState",
        "function roundThirtyPreviewCopy",
        "function roundThirtyPayoffCopy",
        "Round 31 First Bouquet Encore",
        "roundThirtyOnePreview",
        "First Bouquet 7",
        "Round 31 encore First Bouquet payoff",
        "data-round-thirty-one-state=\"tease\"",
        "data-round-thirty-one-state=\"next\"",
        "data-round-thirty-one-state=\"current\"",
        "data-round-thirty-one-state=\"withered\"",
        "data-round-thirty-one-state=\"complete\"",
        "function renderRoundThirtyOnePreview",
        "function roundThirtyOnePreviewState",
        "function roundThirtyOnePreviewCopy",
        "function roundThirtyOnePayoffCopy",
        "Round 32 Moonlit Wreath Encore",
        "roundThirtyTwoPreview",
        "Moonlit Wreath 7",
        "Round 32 encore Moonlit Wreath payoff",
        "data-round-thirty-two-state=\"tease\"",
        "data-round-thirty-two-state=\"next\"",
        "data-round-thirty-two-state=\"current\"",
        "data-round-thirty-two-state=\"withered\"",
        "data-round-thirty-two-state=\"complete\"",
        "function renderRoundThirtyTwoPreview",
        "function roundThirtyTwoPreviewState",
        "function roundThirtyTwoPreviewCopy",
        "function roundThirtyTwoPayoffCopy",
        "Round 33 Bloodroot Compact Encore",
        "roundThirtyThreePreview",
        "Bloodroot Compact 7",
        "Round 33 encore Bloodroot Compact payoff",
        "data-round-thirty-three-state=\"tease\"",
        "data-round-thirty-three-state=\"next\"",
        "data-round-thirty-three-state=\"current\"",
        "data-round-thirty-three-state=\"withered\"",
        "data-round-thirty-three-state=\"complete\"",
        "function renderRoundThirtyThreePreview",
        "function roundThirtyThreePreviewState",
        "function roundThirtyThreePreviewCopy",
        "function roundThirtyThreePayoffCopy",
        "Round 34 Saint's Night Ledger Encore",
        "roundThirtyFourPreview",
        "Saint's Night Ledger 7",
        "Round 34 encore Saint's Night Ledger payoff",
        "data-round-thirty-four-state=\"tease\"",
        "data-round-thirty-four-state=\"next\"",
        "data-round-thirty-four-state=\"current\"",
        "data-round-thirty-four-state=\"withered\"",
        "data-round-thirty-four-state=\"complete\"",
        "function renderRoundThirtyFourPreview",
        "function roundThirtyFourPreviewState",
        "function roundThirtyFourPreviewCopy",
        "function roundThirtyFourPayoffCopy",
        "Round 35 Sub Rosa Grand Bouquet Encore",
        "roundThirtyFivePreview",
        "Sub Rosa Grand Bouquet 7",
        "Round 35 encore Sub Rosa Grand Bouquet payoff",
        "data-round-thirty-five-state=\"tease\"",
        "data-round-thirty-five-state=\"next\"",
        "data-round-thirty-five-state=\"current\"",
        "data-round-thirty-five-state=\"withered\"",
        "data-round-thirty-five-state=\"complete\"",
        "function renderRoundThirtyFivePreview",
        "function roundThirtyFivePreviewState",
        "function roundThirtyFivePreviewCopy",
        "function roundThirtyFivePayoffCopy",
        "Round 36 First Bouquet Encore",
        "roundThirtySixPreview",
        "First Bouquet 8",
        "Round 36 encore First Bouquet payoff",
        "data-round-thirty-six-state=\"tease\"",
        "data-round-thirty-six-state=\"next\"",
        "data-round-thirty-six-state=\"current\"",
        "data-round-thirty-six-state=\"withered\"",
        "data-round-thirty-six-state=\"complete\"",
        "function renderRoundThirtySixPreview",
        "function roundThirtySixPreviewState",
        "function roundThirtySixPreviewCopy",
        "function roundThirtySixPayoffCopy",
        "Round 37 Moonlit Wreath Encore",
        "roundThirtySevenPreview",
        "Moonlit Wreath 8",
        "Round 37 encore Moonlit Wreath payoff",
        "data-round-thirty-seven-state=\"tease\"",
        "data-round-thirty-seven-state=\"next\"",
        "data-round-thirty-seven-state=\"current\"",
        "data-round-thirty-seven-state=\"withered\"",
        "data-round-thirty-seven-state=\"complete\"",
        "function renderRoundThirtySevenPreview",
        "function roundThirtySevenPreviewState",
        "function roundThirtySevenPreviewCopy",
        "function roundThirtySevenPayoffCopy",
        "Round 38 Bloodroot Compact Encore",
        "roundThirtyEightPreview",
        "Bloodroot Compact 8",
        "Round 38 encore Bloodroot Compact payoff",
        "data-round-thirty-eight-state=\"tease\"",
        "data-round-thirty-eight-state=\"next\"",
        "data-round-thirty-eight-state=\"current\"",
        "data-round-thirty-eight-state=\"withered\"",
        "data-round-thirty-eight-state=\"complete\"",
        "function renderRoundThirtyEightPreview",
        "function roundThirtyEightPreviewState",
        "function roundThirtyEightPreviewCopy",
        "function roundThirtyEightPayoffCopy",
        "Round 39 Saint's Night Ledger Encore",
        "roundThirtyNinePreview",
        "Saint's Night Ledger 8",
        "Round 39 encore Saint's Night Ledger payoff",
        "data-round-thirty-nine-state=\"tease\"",
        "data-round-thirty-nine-state=\"next\"",
        "data-round-thirty-nine-state=\"current\"",
        "data-round-thirty-nine-state=\"withered\"",
        "data-round-thirty-nine-state=\"complete\"",
        "function renderRoundThirtyNinePreview",
        "function roundThirtyNinePreviewState",
        "function roundThirtyNinePreviewCopy",
        "function roundThirtyNinePayoffCopy",
        "Round 40 Sub Rosa Grand Bouquet Encore",
        "roundFortyPreview",
        "Sub Rosa Grand Bouquet 8",
        "Round 40 encore Sub Rosa Grand Bouquet payoff",
        "data-round-forty-state=\"tease\"",
        "data-round-forty-state=\"next\"",
        "data-round-forty-state=\"current\"",
        "data-round-forty-state=\"withered\"",
        "data-round-forty-state=\"complete\"",
        "function renderRoundFortyPreview",
        "function roundFortyPreviewState",
        "function roundFortyPreviewCopy",
        "function roundFortyPayoffCopy",
        "Round 41 First Bouquet Encore",
        "roundFortyOnePreview",
        "First Bouquet 9",
        "Round 41 encore First Bouquet payoff",
        "data-round-forty-one-state=\"tease\"",
        "data-round-forty-one-state=\"next\"",
        "data-round-forty-one-state=\"current\"",
        "data-round-forty-one-state=\"withered\"",
        "data-round-forty-one-state=\"complete\"",
        "function renderRoundFortyOnePreview",
        "function roundFortyOnePreviewState",
        "function roundFortyOnePreviewCopy",
        "function roundFortyOnePayoffCopy",
        "Round 42 Moonlit Wreath Encore",
        "roundFortyTwoPreview",
        "Moonlit Wreath 9",
        "Round 42 encore Moonlit Wreath payoff",
        "data-round-forty-two-state=\"tease\"",
        "data-round-forty-two-state=\"next\"",
        "data-round-forty-two-state=\"current\"",
        "data-round-forty-two-state=\"withered\"",
        "data-round-forty-two-state=\"complete\"",
        "function renderRoundFortyTwoPreview",
        "function roundFortyTwoPreviewState",
        "function roundFortyTwoPreviewCopy",
        "function roundFortyTwoPayoffCopy",
        "Round 43 Bloodroot Compact Encore",
        "roundFortyThreePreview",
        "Bloodroot Compact 9",
        "Round 43 encore Bloodroot Compact payoff",
        "data-round-forty-three-state=\"tease\"",
        "data-round-forty-three-state=\"next\"",
        "data-round-forty-three-state=\"current\"",
        "data-round-forty-three-state=\"withered\"",
        "data-round-forty-three-state=\"complete\"",
        "function renderRoundFortyThreePreview",
        "function roundFortyThreePreviewState",
        "function roundFortyThreePreviewCopy",
        "function roundFortyThreePayoffCopy",
        "Round 44 Saint's Night Ledger Encore",
        "roundFortyFourPreview",
        "Saint's Night Ledger 9",
        "Round 44 encore Saint's Night Ledger payoff",
        "data-round-forty-four-state=\"tease\"",
        "data-round-forty-four-state=\"next\"",
        "data-round-forty-four-state=\"current\"",
        "data-round-forty-four-state=\"withered\"",
        "data-round-forty-four-state=\"complete\"",
        "function renderRoundFortyFourPreview",
        "function roundFortyFourPreviewState",
        "function roundFortyFourPreviewCopy",
        "function roundFortyFourPayoffCopy",
        "Round 45 Sub Rosa Grand Bouquet Encore",
        "roundFortyFivePreview",
        "Sub Rosa Grand Bouquet 9",
        "Round 45 encore Sub Rosa Grand Bouquet payoff",
        "data-round-forty-five-state=\"tease\"",
        "data-round-forty-five-state=\"next\"",
        "data-round-forty-five-state=\"current\"",
        "data-round-forty-five-state=\"withered\"",
        "data-round-forty-five-state=\"complete\"",
        "function renderRoundFortyFivePreview",
        "function roundFortyFivePreviewState",
        "function roundFortyFivePreviewCopy",
        "function roundFortyFivePayoffCopy",
        "Round 46 First Bouquet Encore",
        "roundFortySixPreview",
        "First Bouquet 10",
        "Round 46 encore First Bouquet payoff",
        "data-round-forty-six-state=\"tease\"",
        "data-round-forty-six-state=\"next\"",
        "data-round-forty-six-state=\"current\"",
        "data-round-forty-six-state=\"withered\"",
        "data-round-forty-six-state=\"complete\"",
        "function renderRoundFortySixPreview",
        "function roundFortySixPreviewState",
        "function roundFortySixPreviewCopy",
        "function roundFortySixPayoffCopy",
        "Round 47 Moonlit Wreath Encore",
        "roundFortySevenPreview",
        "Moonlit Wreath 10",
        "Round 47 encore Moonlit Wreath payoff",
        "data-round-forty-seven-state=\"tease\"",
        "data-round-forty-seven-state=\"next\"",
        "data-round-forty-seven-state=\"current\"",
        "data-round-forty-seven-state=\"withered\"",
        "data-round-forty-seven-state=\"complete\"",
        "function renderRoundFortySevenPreview",
        "function roundFortySevenPreviewState",
        "function roundFortySevenPreviewCopy",
        "function roundFortySevenPayoffCopy",
        "Round 48 Bloodroot Compact Encore",
        "roundFortyEightPreview",
        "Bloodroot Compact 10",
        "Round 48 encore Bloodroot Compact payoff",
        "data-round-forty-eight-state=\"tease\"",
        "data-round-forty-eight-state=\"next\"",
        "data-round-forty-eight-state=\"current\"",
        "data-round-forty-eight-state=\"withered\"",
        "data-round-forty-eight-state=\"complete\"",
        "function renderRoundFortyEightPreview",
        "function roundFortyEightPreviewState",
        "function roundFortyEightPreviewCopy",
        "function roundFortyEightPayoffCopy",
        "Round 49 Saint's Night Ledger Encore",
        "roundFortyNinePreview",
        "Saint's Night Ledger 10",
        "Round 49 encore Saint's Night Ledger payoff",
        "data-round-forty-nine-state=\"tease\"",
        "data-round-forty-nine-state=\"next\"",
        "data-round-forty-nine-state=\"current\"",
        "data-round-forty-nine-state=\"withered\"",
        "data-round-forty-nine-state=\"complete\"",
        "function renderRoundFortyNinePreview",
        "function roundFortyNinePreviewState",
        "function roundFortyNinePreviewCopy",
        "function roundFortyNinePayoffCopy",
        "Round 50 Sub Rosa Grand Bouquet Encore",
        "roundFiftyPreview",
        "Sub Rosa Grand Bouquet 10",
        "Round 50 encore Sub Rosa Grand Bouquet payoff",
        "data-round-fifty-state=\"tease\"",
        "data-round-fifty-state=\"next\"",
        "data-round-fifty-state=\"current\"",
        "data-round-fifty-state=\"withered\"",
        "data-round-fifty-state=\"complete\"",
        "function renderRoundFiftyPreview",
        "function roundFiftyPreviewState",
        "function roundFiftyPreviewCopy",
        "function roundFiftyPayoffCopy",
        "Round 51 First Bouquet Encore",
        "roundFiftyOnePreview",
        "First Bouquet 11",
        "Round 51 encore First Bouquet payoff",
        "data-round-fifty-one-state=\"tease\"",
        "data-round-fifty-one-state=\"next\"",
        "data-round-fifty-one-state=\"current\"",
        "data-round-fifty-one-state=\"withered\"",
        "data-round-fifty-one-state=\"complete\"",
        "function renderRoundFiftyOnePreview",
        "function roundFiftyOnePreviewState",
        "function roundFiftyOnePreviewCopy",
        "function roundFiftyOnePayoffCopy",
        "Round 52 Moonlit Wreath Encore",
        "roundFiftyTwoPreview",
        "Moonlit Wreath 11",
        "Round 52 encore Moonlit Wreath payoff",
        "data-round-fifty-two-state=\"tease\"",
        "data-round-fifty-two-state=\"next\"",
        "data-round-fifty-two-state=\"current\"",
        "data-round-fifty-two-state=\"withered\"",
        "data-round-fifty-two-state=\"complete\"",
        "function renderRoundFiftyTwoPreview",
        "function roundFiftyTwoPreviewState",
        "function roundFiftyTwoPreviewCopy",
        "function roundFiftyTwoPayoffCopy",
        "Round 53 Bloodroot Compact Encore",
        "roundFiftyThreePreview",
        "Bloodroot Compact 11",
        "Round 53 encore Bloodroot Compact payoff",
        "data-round-fifty-three-state=\"tease\"",
        "data-round-fifty-three-state=\"next\"",
        "data-round-fifty-three-state=\"current\"",
        "data-round-fifty-three-state=\"withered\"",
        "data-round-fifty-three-state=\"complete\"",
        "function renderRoundFiftyThreePreview",
        "function roundFiftyThreePreviewState",
        "function roundFiftyThreePreviewCopy",
        "function roundFiftyThreePayoffCopy",
        "Round 54 Saint's Night Ledger Encore",
        "roundFiftyFourPreview",
        "Saint's Night Ledger 11",
        "Round 54 encore Saint's Night Ledger payoff",
        "data-round-fifty-four-state=\"tease\"",
        "data-round-fifty-four-state=\"next\"",
        "data-round-fifty-four-state=\"current\"",
        "data-round-fifty-four-state=\"withered\"",
        "data-round-fifty-four-state=\"complete\"",
        "function renderRoundFiftyFourPreview",
        "function roundFiftyFourPreviewState",
        "function roundFiftyFourPreviewCopy",
        "function roundFiftyFourPayoffCopy",
        "Round 55 Sub Rosa Grand Bouquet Encore",
        "roundFiftyFivePreview",
        "Sub Rosa Grand Bouquet 11",
        "Round 55 encore Sub Rosa Grand Bouquet payoff",
        "data-round-fifty-five-state=\"tease\"",
        "data-round-fifty-five-state=\"next\"",
        "data-round-fifty-five-state=\"current\"",
        "data-round-fifty-five-state=\"withered\"",
        "data-round-fifty-five-state=\"complete\"",
        "function renderRoundFiftyFivePreview",
        "function roundFiftyFivePreviewState",
        "function roundFiftyFivePreviewCopy",
        "function roundFiftyFivePayoffCopy",
        "Round 56 First Bouquet Encore",
        "roundFiftySixPreview",
        "First Bouquet 12",
        "Round 56 encore First Bouquet payoff",
        "data-round-fifty-six-state=\"tease\"",
        "data-round-fifty-six-state=\"next\"",
        "data-round-fifty-six-state=\"current\"",
        "data-round-fifty-six-state=\"withered\"",
        "data-round-fifty-six-state=\"complete\"",
        "function renderRoundFiftySixPreview",
        "function roundFiftySixPreviewState",
        "function roundFiftySixPreviewCopy",
        "function roundFiftySixPayoffCopy",
        "Round 57 Moonlit Wreath Encore",
        "roundFiftySevenPreview",
        "Moonlit Wreath 12",
        "Round 57 encore Moonlit Wreath payoff",
        "data-round-fifty-seven-state=\"tease\"",
        "data-round-fifty-seven-state=\"next\"",
        "data-round-fifty-seven-state=\"current\"",
        "data-round-fifty-seven-state=\"withered\"",
        "data-round-fifty-seven-state=\"complete\"",
        "function renderRoundFiftySevenPreview",
        "function roundFiftySevenPreviewState",
        "function roundFiftySevenPreviewCopy",
        "function roundFiftySevenPayoffCopy",
        "shapeBloomBtn",
        "Shape Bloom",
        "Black Candle Vine",
        "function lineRelicForMatch",
        "function queueLineRelicBurst",
        "function lineRelicMessage",
        "line4",
        "Eclipse Seed Rune",
        "function rareSeedRuneForMatch",
        "function queueRareSeedRuneBurst",
        "function rareSeedRuneMessage",
        "line5",
        "seed-rune",
        "Rune-Tended Soil",
        "function plantEclipseSeedRune",
        "data-action=\"plant-eclipse-seed-rune\"",
        "pendingRuneTendedSoil",
        "activeRuneTendedSoil",
        "Pruning Shears",
        "pruningShearsBtn",
        "pruningShearsCount",
        "boosterPanel",
        "function togglePruningShears",
        "function usePruningShears",
        "function queuePruningShearBurst",
        "shears-target",
        "boosters.pruningShears",
        "Moonwater Flask",
        "moonwaterFlaskBtn",
        "moonwaterFlaskCount",
        "function toggleMoonwaterFlask",
        "function useMoonwaterFlask",
        "function moonwaterPatchCells",
        "function shuffleMoonwaterPatch",
        "function queueMoonwaterBurst",
        "moonwater-target",
        "moonwater-area",
        "boosters.moonwaterFlask",
        "Black Candle",
        "blackCandleBtn",
        "blackCandleCount",
        "blackCandleModes",
        "blackCandleAxis",
        "function toggleBlackCandle",
        "function useBlackCandle",
        "function blackCandleLineCells",
        "function refillBlackCandleLine",
        "function queueBlackCandleBurst",
        "black-candle-line",
        "boosters.blackCandle",
        "Grave Soil",
        "graveSoilBtn",
        "graveSoilCount",
        "graveSoilCells",
        "function toggleGraveSoil",
        "function useGraveSoil",
        "function queueGraveSoilBurst",
        "function graveSoilRelicForMatch",
        "function isGraveSoilEligible",
        "grave-soil-target",
        "grave-soil-ready",
        "boosters.graveSoil",
        "activeBooster",
        "Cursed Thorn",
        "thornGoal",
        "cursed-thorn-overlay",
        "thorn-teach",
        "thorn-teach-marker",
        "thornObjectiveHint",
        "Match beside Cursed Thorns",
        "Cursed Thorn lesson",
        "function seedRoundTwoThornTeachingMove",
        "function roundTwoThornTeachingSwap",
        "function hasRoundTwoThornTeachingMove",
        "function cellsTouchCursedThorn",
        "function damageAdjacentThorns",
        "function thornDamageMessage",
        "shapeDiscoveryHint",
        "L/T/cross = Shape Bloom",
        "function shapeDiscoveryHintMarkup",
        "function patternDiscoveryCopy",
        "vial-meter",
        "data-vial=\"SAP\"",
        "let moves = roundTemplates[0].moves",
        "event.key.toLowerCase() === \"n\"",
        "function seedCurrentTargetMoves",
        "writeTargetLegalMovePatch(4, 0, targetIds[1], 4)",
        "function writeTargetLegalMovePatch(originX, originY, flowerId, lineLength = 3)",
        "function seedRoundOneBlackCandleVineLesson",
        "function findTargetLegalMove",
        "function nextTargetMoveHint",
        "findTargetLegalMove(target.flowerId, targetIndex)",
        "Next Bouquet",
        "roundCeremony",
        "factionXpFill",
        "apothecary-fill",
    ]
    missing = [needle for needle in required if needle not in html]
    if missing:
        raise SystemExit(f"Missing HTML match-shape hooks: {missing}")


verify_source_hooks()
assert_single_shape("horizontal line", [(1, 1), (2, 1), (3, 1)], "line")
assert_single_shape("vertical line", [(4, 1), (4, 2), (4, 3)], "line")
assert_single_shape("four line relic", [(2, 3), (3, 3), (4, 3), (5, 3)], "line")
assert_single_shape("five line seed rune", [(1, 3), (2, 3), (3, 3), (4, 3), (5, 3)], "line")
assert_single_shape("l shape", [(2, 2), (3, 2), (4, 2), (2, 3), (2, 4)], "l")
assert_single_shape("t shape", [(2, 3), (3, 3), (4, 3), (3, 4), (3, 5)], "t")
assert_single_shape("cross shape", [(3, 3), (2, 3), (4, 3), (3, 2), (3, 4)], "cross")
assert_no_match("diagonal-only cluster", [(2, 2), (3, 3), (4, 4)])

print("HTML match-shape regression checks passed.")
