from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
HTML = ROOT / "playable" / "midnight_bloom_prototype.html"
BOARD_SIZE = 8
SHAPE_VALUE = 2
BASE_VALUES = [0, 1, 3, 4, 5]
ALTAR_TILE_ASSETS = [
    "assets/tiles/96/withered_sun_medallion.png",
    "assets/tiles/96/bone_white_thorn_star.png",
    "assets/tiles/96/purple_nightshade_bloom.png",
    "assets/tiles/96/bloodroot_ruby_shard.png",
    "assets/tiles/96/amber_resin_seed.png",
    "assets/tiles/96/crimson_rose_rune.png",
    "assets/tiles/48/withered_sun_medallion.png",
    "assets/tiles/48/bone_white_thorn_star.png",
    "assets/tiles/48/purple_nightshade_bloom.png",
    "assets/tiles/48/bloodroot_ruby_shard.png",
    "assets/tiles/48/amber_resin_seed.png",
    "assets/tiles/48/crimson_rose_rune.png",
    "assets/tiles/altar/cursed_thorn_seal.svg",
]


def make_board(shape_cells):
    board = [
        [BASE_VALUES[(x + y * 2) % len(BASE_VALUES)] for x in range(BOARD_SIZE)]
        for y in range(BOARD_SIZE)
    ]
    for x, y in shape_cells:
        board[y][x] = SHAPE_VALUE
    return board


def png_dimensions(path):
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise SystemExit(f"Tile asset is not a PNG: {path}")
    return int.from_bytes(data[16:20], "big"), int.from_bytes(data[20:24], "big")


def find_run_segments(board):
    segments = []
    for y in range(BOARD_SIZE):
        start = 0
        for x in range(1, BOARD_SIZE + 1):
            if x == BOARD_SIZE or board[y][x] != board[y][start]:
                if board[y][start] is not None and x - start >= 3:
                    segments.append({
                        "val": board[y][start],
                        "direction": "horizontal",
                        "cells": [(mx, y) for mx in range(start, x)],
                    })
                start = x

    for x in range(BOARD_SIZE):
        start = 0
        for y in range(1, BOARD_SIZE + 1):
            if y == BOARD_SIZE or board[y][x] != board[start][x]:
                if board[start][x] is not None and y - start >= 3:
                    segments.append({
                        "val": board[start][x],
                        "direction": "vertical",
                        "cells": [(x, my) for my in range(start, y)],
                    })
                start = y
    return segments


def matches(board):
    segments = find_run_segments(board)
    parents = list(range(len(segments)))

    def find(index):
        if parents[index] != index:
            parents[index] = find(parents[index])
        return parents[index]

    def union(a, b):
        root_a = find(a)
        root_b = find(b)
        if root_a != root_b:
            parents[root_b] = root_a

    owners_by_cell = {}
    for index, segment in enumerate(segments):
        for cell in segment["cells"]:
            owners = owners_by_cell.setdefault(cell, [])
            for owner in owners:
                union(index, owner)
            owners.append(index)

    groups = {}
    for index, segment in enumerate(segments):
        root = find(index)
        group = groups.setdefault(root, {
            "val": segment["val"],
            "cells": set(),
            "runs": [],
        })
        group["cells"].update(segment["cells"])
        group["runs"].append(segment)

    found = []
    for group in groups.values():
        cells = sorted(group["cells"], key=lambda cell: (cell[1], cell[0]))
        found.append({
            "val": group["val"],
            "cells": cells,
            "len": len(cells),
            "runs": group["runs"],
            "shape": classify_shape(cells, group["runs"]),
        })
    return sorted(found, key=lambda match: match["len"], reverse=True)


def classify_shape(cells, runs):
    horizontal = [run for run in runs if run["direction"] == "horizontal"]
    vertical = [run for run in runs if run["direction"] == "vertical"]
    if not horizontal or not vertical:
        return "line"

    cell_set = set(cells)
    intersections = []
    for h_run in horizontal:
        h_cells = set(h_run["cells"])
        for v_run in vertical:
            intersections.extend(cell for cell in v_run["cells"] if cell in h_cells)

    best_arms = 0
    for x, y in intersections:
        arms = sum((
            (x - 1, y) in cell_set,
            (x + 1, y) in cell_set,
            (x, y - 1) in cell_set,
            (x, y + 1) in cell_set,
        ))
        best_arms = max(best_arms, arms)

    if best_arms >= 4:
        return "cross"
    if best_arms == 3:
        return "t"
    return "l"


def assert_single_shape(name, cells, expected_kind):
    found = matches(make_board(cells))
    if len(found) != 1:
        raise SystemExit(f"{name}: expected 1 match, found {len(found)}: {found}")
    match = found[0]
    expected_cells = sorted(cells, key=lambda cell: (cell[1], cell[0]))
    if match["cells"] != expected_cells:
        raise SystemExit(f"{name}: cleared {match['cells']} instead of {expected_cells}")
    if match["shape"] != expected_kind:
        raise SystemExit(f"{name}: classified as {match['shape']} instead of {expected_kind}")


def assert_no_match(name, cells):
    found = matches(make_board(cells))
    if found:
        raise SystemExit(f"{name}: expected no match, found {found}")


def verify_source_hooks():
    html = HTML.read_text()
    required = [
        "function analyzeMatchShape",
        "shapeAuditData",
        "function analyzeBoardSnapshot",
        "Prototype match-shape review hook",
        "Witch's Cross!",
        "Night Garden L-Bloom!",
        "Twin Stem Bloom!",
        "function demoMatchShape",
        "const maxCascades",
        "resolveAnimated({ maxCascades: 1 })",
        "const roundTemplates",
        "const FOCUSED_LEVEL_COUNT = 3",
        "Math.min(FOCUSED_LEVEL_COUNT, Math.max(1, Number(roundNumber) || 1))",
        "function maybeCompleteRound",
        "function demoCompleteBouquet",
        "demoCompleteBtn",
        "Complete Bouquet",
        "round-one-active",
        "body.round-one-active:not(.first-move-made) #shuffleBtn",
        "firstSwapCue",
        "Swap the glowing pair",
        "swap-path-arrow",
        "function renderFirstSwapArrow(boardEl)",
        "renderFirstSwapArrow(boardEl);",
        "swap-arrow-pulse",
        "round-one-black-candle-cue",
        "Make 4 Bone Stars - Black Candle Vine burns a row.",
        "Black Candle Vine! ${lane} cleared.",
        "${lane} cleared; the First Bouquet is ready to seal.",
        "round-one-followup-cue",
        "Keep matching - swap the glowing pair.",
        "round-one-refused",
        "Swap the glowing pair to open the next harvest.",
        "function restoreFirstSwapCueAfterRefusal({ preserveCue = false } = {})",
        "if (preserveCue)",
        "restoreFirstSwapCueAfterRefusal({ preserveCue: true });",
        "first-swap-cue::before",
        "GLYPH GUIDE",
        "BLACK CANDLE",
        "body.round-one-active.round-one-black-candle-cue .first-swap-cue { position:relative; z-index:12; }",
        "moves-counter",
        "body.round-one-active .objective-target",
        "function firstSwapCueText(a, b)",
        "function primeFocusedFirstMoveHint",
        "Crack the marked thorns",
        "cursed_thorn_seal.svg",
        "function thornSealMarkup",
        "cursed-thorn-art",
        "thorn-root",
        "thorn-art-shatter",
        "thorn-lesson-active",
        "function focusedRoundTwoHarvestSummary(result)",
        "isFirstValidMove && currentRound === 1",
        ".map((target) => `+${result.gained[target.flowerId]} ${flowers[target.flowerId][0]}`)",
        "Follow the glow.",
        "isRestoredNextOrderFocus() || isPostOnboardingIdleHintActive()",
        "RESTORED_ROUND_TWO_GUIDE_LIMIT",
        "let restoredRoundTwoGuideMoves = 0",
        "function isRestoredRoundTwoWindow()",
        "function isRestoredRoundTwoGuideActive()",
        "function isPostOnboardingIdleHintActive()",
        "round-two-followup-cue",
        "NEXT BLOOM",
        "${flowers[remainingTarget.flowerId][0]} next ${direction}",
        "const postOnboardingIdleHint = isPostOnboardingIdleHintActive();",
        "restoredRoundTwoGuideMoves >= RESTORED_ROUND_TWO_GUIDE_LIMIT",
        "const reachedRestoredGuideLimit = guidedRoundTwoLesson",
        "isRestoredRoundTwoGuideActive()",
        "? 650",
        "swap-snap",
        "activeSwapCells",
        "valid-swap",
        "let validSwapCells = new Set()",
        "function clearTransientGameFeel()",
        '".objective-flight, .bouquet-bind-seal, .greenhouse-intake-flight"',
        "const launchRound = currentRound;",
        "if (currentRound !== launchRound)",
        "<strong>First bloom!</strong> Your bouquet is already taking shape.",
        "Keep the authored opening three-match from randomly extending",
        "board[originY][originX + 3] = fillerB;",
        "board[originY + 2][originX + 1] = fillerD;",
        "board[originY][originX - 1] = fillerC;",
        "const authoredRoundOneLesson = currentRound === 1",
        "{ maxCascades: 1, quietReseed: true }",
        "const ALTAR_DRIFT_FOCUSED_BAITS = 1",
        "function prepareAltarDriftRefill(options = {})",
        "function seedAltarDriftCascade()",
        "const guidedRoundTwoLesson = isRestoredRoundTwoGuideActive();",
        "{ maxCascades: 1, quietReseed: true, suppressAltarDrift: true }",
        "options.suppressAltarDrift",
        "function finishResolve(result, options = {})",
        "function launchObjectiveFlights(gained, gainedCells = [])",
        "function visibleGreenhouseIntakeTarget()",
        "$(\"restoredGreenhouseStatus\")",
        "$(\"mobileRestorationDial\")",
        "const targetEl = visibleGreenhouseIntakeTarget();",
        "will-change: transform, opacity;",
        "function queueBouquetBindingSeal",
        "bouquet-bind-seal",
        ".bouquet-bind-seal { width:84px; min-height:36px;",
        "objective-target-fill",
        "function bouquetAssemblyMarkup",
        "bouquet-assembly-ring",
        "bouquet-ingredient-bind",
        "trophy.dataset.assemblyState = bouquetSealPulseActive ? \"forming\" : \"assembled\";",
        "bouquet-binding-vine",
        "objective-target-seal",
        "restoration-veil",
        "restoration-cracks",
        "restoration-root-web",
        "restoration-glass-rays",
        "restoration-coin-stream",
        "restoration-before-label",
        "restoration-after-label",
        "restoration-coin-into-glass",
        "Spend the bouquet payout to relight the abandoned glass.",
        "Next Order → Moonlit Wreath",
        "greenhouse-upgrade-ladder",
        "function renderGreenhouseUpgradeLadders()",
        "Bloodroot Conservatory",
        "body.restored-next-order-focus .greenhouse-order-ladder { display:none; }",
        "body.restored-next-order-focus:not(.restored-greenhouse-handoff) .restored-greenhouse-status { display:none; }",
        "document.body.classList.toggle(\"restored-next-order-focus\", isRestoredRoundTwoWindow() || failedFocusedRestoredOrder);",
        "document.body.classList.toggle(\"restored-next-order-guide\", isRestoredNextOrderFocus());",
        "const preserveCompletedRoundTwoGuide = retryingFailedBouquet",
        "if (!preserveCompletedRoundTwoGuide)",
        "display: grid;\n        grid-template-columns: repeat(4, minmax(0, 1fr));",
        "thornGoalComplete(plan) || isRestoredRoundTwoGuideActive()",
        "calc(100vh - 262px)",
        "objective-goal-joiner",
        "clip-path: inset(50%);",
        "order-fill",
        "style=\"--target-pct:${pct}%\"",
        "style=\"--order-pct:${pct}%\"",
        "gainedCells: flowers.map(() => [])",
        "pulseOrderCounts(result.gained, result.gainedCells)",
        "const originX = boardRect.left + ((origin[0] + 0.5) / BOARD_SIZE) * boardRect.width;",
        "objective-flight",
        "objective-target.order-pulse::after",
        "objective-sip",
        "flight.src = flowers[target.flowerId][1]",
        "No bloom — follow the glowing pair.",
        "const focusedCueActive = (currentRound === 1 || isRestoredNextOrderFocus())",
        "swap-refused",
        "function restoreFirstSwapCueAfterRefusal",
        "restoreFirstSwapCueAfterRefusal();",
        "isRestoredRoundTwoGuideActive() && hasMadeValidMove && target",
        "function shouldPreserveSelectedHintPair",
        "const selectedHintPair = new Set(idleHintCells);",
        "idleHintCells = selectedHintPair;",
        "body.focused-slice-failed #shuffleBtn",
        "body.focused-slice-failed .bottom",
        "body.focused-slice-failed #renewBtn.visible",
        "function finishTileSwipe(event, x, y)",
        "SWIPE_THRESHOLD",
        "function boardTileFromEvent(event)",
        "function handleBoardPointerDown(event)",
        "$(\"board\").addEventListener(\"pointerdown\", handleBoardPointerDown)",
        "$(\"board\").addEventListener(\"click\", handleBoardClick)",
        "tile.setPointerCapture(event.pointerId)",
        "function pulseHaptic(pattern)",
        "pulseHaptic(18)",
        "pulseHaptic([10, 35, 18])",
        "let bloomAudioContext = null",
        "let bloomAudioMaster = null",
        "let bloomSoundscape = null",
        "let bloomAudioVoiceCount = 0",
        "let bloomAudioEvents = []",
        "function recordBloomAudioEvent(kind, detail = {})",
        "function bloomStageScale(stageKey = activeGreenhouseStageKey())",
        "function bloomScaleTone(index, octave = 1, stageKey = activeGreenhouseStageKey())",
        "function duckBloomSoundscape(depth = 0.45, duration = 0.75)",
        "function playBloomChord(frequencies, startOffset, duration",
        "function playBloomRitualPulse(startOffset, strength = 1",
        "window.__bloomAudioProbe = () => ({",
        "function bloomAudioCtx()",
        "function setupBloomAudioGraph(ctx)",
        "function soundscapeSettings(stageKey = bloomAudioStageKey)",
        "function ensureBloomSoundscape()",
        "function updateBloomSoundscapeStage(stageKey",
        "playBloomNoise(0, 0.085 + cascade * 0.02",
        "bloomAudioVoiceCount += 1",
        "recordBloomAudioEvent(kind, detail)",
        "updateBloomSoundscapeStage(activeGreenhouseStageKey())",
        "function playBloomTone(frequency, startOffset, duration, gain = 0.028, type = \"sine\", options = {})",
        "function playBloomSound(kind, detail = {})",
        "playBloomSound(\"swap\")",
        "playBloomSound(\"invalid\")",
        ".tile.invalid-swap::after",
        "@keyframes invalid-swap-mark",
        "playBloomSound(\"match\", {",
        "cleared: wave.clearCells.length",
        "shape: Boolean(wave.strongestShape)",
        "flowerId: board[wave.clearCells[0]?.[1]]?.[wave.clearCells[0]?.[0]]",
        "playBloomSound(\"complete\")",
        "playBloomSound(retryingFailedBouquet ? \"retry\" : \"handoff\")",
        "playBloomSound(\"handoff\")",
        "playBloomSound(\"restore\")",
        "let swapGlideCells = new Map()",
        "function markSwapGlide(a, b)",
        "function clearSwapGlide()",
        "swap-glide",
        "@keyframes swap-glide",
        "function previewSwapMatches",
        "function selectedHarvestPreviewFor",
        "const harvestPreview = selectedHarvestPreviewFor(selected)",
        "match-preview",
        "match-preview-anchor",
        "relic-preview",
        "in selected harvest preview",
        "Black Candle Vine lane preview",
        "--tile-color",
        "harvest-ready-throb",
        "let currentCascadeWave = 0",
        "let lastSettledCascadeCount = 0",
        "function queueCascadeImpact(wave, cascadeIndex = 0)",
        "function queueSettleSparks(cascadeIndex = 0)",
        "const visibleResourceCells = new Set(dedupeCells(wave.clearCells)",
        "visibleResourceCells.has(`${x},${y}`)",
        "cascade-ring",
        "impact-sigil",
        'text: cascadeIndex > 0 ? `x${cascadeIndex + 1}` : "HIT"',
        "cascade-vein",
        ".sort((a, b) => (b.cells.length - a.cells.length))[0]",
        "delay: 42",
        "matchRuns",
        "settle-spark",
        "playBloomSound(\"settle\"",
        "cascade-wave-label",
        "boardEl.dataset.cascadeWave",
        "boardEl.dataset.lastCascadeCount",
        "scheduleBoardParticleClear(result.cascades)",
        "const WILD_CHAIN_CASCADE_BONUS",
        "function applyWildChainBonus",
        "function queueWildChainPayoff",
        "function wildChainMessage",
        "wild-chain-banner",
        "boardEl.dataset.lastWildChainBonus",
        "chain-payoff",
        "Wild Chain x${result.wildChain.cascades}",
        "@keyframes cascade-ring",
        "@keyframes impact-sigil-bloom",
        "@keyframes cascade-vein-strike",
        "thorn-event",
        "thorn-event-stamp",
        "thorn-shock",
        "@keyframes thorn-shock",
        "${thornHitClass ? `<span class=\"thorn-event\">${thornClearedClass ? \"BREAK\" : \"CRACK\"}</span>` : \"\"}",
        "@keyframes wild-chain-banner",
        ".board.chain-payoff",
        ".board-particle.chain-lash",
        "coins total",
        "bonus coins included",
        "data-flower-id",
        "occult_altar_socket.svg",
        "--board-stage-glow",
        "body[data-active-greenhouse-stage=\"moonlit\"] .board",
        "body[data-active-greenhouse-stage=\"bloodroot\"] .board",
        "roundOneRestoration",
        "coin-payoff",
        "coin-payoff-flight",
        "id=\"coinPayoff\"",
        "id=\"bouquetTrophy\"",
        "data-bouquet-payoff-state=\"sealed\"",
        "function renderBouquetTrophy",
        "function pulseBouquetSealFeedback()",
        "function pulseNextOrderReady()",
        "bouquet-sealed",
        "next-order-ready",
        "bouquet-trophy",
        "Sealed Order",
        "Bloodroot and Sol Rot seal the conservatory run.",
        "restoration-awakening",
        "restoration-flare",
        "restoration-spark-field",
        "restored-glass-reveal",
        "withered-glass-fall",
        "panel.classList.add(\"restoration-awakening\")",
        "greenhouse-awakening",
        "first_greenhouse_withered.jpg",
        "first_greenhouse_restored.jpg",
        "moonlit_wreath_greenhouse.jpg",
        "bloodroot_compact_greenhouse.jpg",
        "greenhouse-art-withered",
        "greenhouse-art-restored",
        "const greenhouseArtwork = {",
        "function applyGreenhouseArtwork(stageKey)",
        "scene.dataset.greenhouseArt = stageKey",
        "const BLOODROOT_CONSERVATORY_COST = 180",
        "let roundThreeConservatoryRaised = false",
        "roundThreeConservatoryRaised,",
        "roundThreeConservatoryRaised = Boolean(state.roundThreeConservatoryRaised || currentRound > 3)",
        "const roundThreeFinalPending = currentRound === 3 && roundComplete && !roundThreeConservatoryRaised;",
        "const roundThreeFinalPayoff = roundThreeFinalPending || roundThreeFinalComplete;",
        "applyGreenhouseArtwork(payoffCeremony.artKey)",
        "round-three-final-pending",
        "BLOODROOT CONSERVATORY READY",
        "Raise Conservatory · ${BLOODROOT_CONSERVATORY_COST} coins",
        "function raiseRoundThreeConservatory()",
        "roundThreeConservatoryRaised = true;",
        "Spend the Bloodroot payout to raise the conservatory.",
        "active-greenhouse-stage",
        "id=\"activeGreenhouseStage\"",
        "const activeGreenhouseStages = {",
        "function activeGreenhouseStageKey()",
        "function applyActiveGreenhouseStage(stageKey)",
        "document.body.dataset.activeGreenhouseStage = stageKey",
        "main.dataset.stageLabel = stage.shortLabel",
        "--active-greenhouse-image",
        "content:attr(data-stage-label)",
        "var(--active-greenhouse-image, url(\"../assets/greenhouse/first_greenhouse_withered.jpg\")) center / cover no-repeat",
        "var(--active-greenhouse-image, url(\"../assets/greenhouse/first_greenhouse_withered.jpg\")) center bottom / cover no-repeat",
        "applyActiveGreenhouseStage(activeGreenhouseStageKey())",
        "body.round-one-active .active-greenhouse-stage",
        "body.restored-next-order-focus .active-greenhouse-stage",
        "body.restored-next-order-focus .active-greenhouse-badge",
        "body.round-one-active .hero::before",
        "hero-greenhouse-depth",
        "active-greenhouse-depth",
        "greenhouse-rib",
        "greenhouse-lamp",
        "greenhouse-vine",
        "greenhouse-bed",
        "greenhouse-mist",
        "greenhouse-revival-light",
        "greenhouse-revival-vines",
        "greenhouse-revival-sigil",
        "function greenhouseRevivalTier(pct)",
        "function applyActiveGreenhouseRevival(progress = roundProgress(activeRoundPlan()))",
        "document.body.dataset.greenhouseRevivalTier = String(tier)",
        "data-greenhouse-revival-tier",
        "--greenhouse-revival-pct",
        "--greenhouse-revival-alpha",
        "greenhouse-restoration-dial",
        "id=\"heroRestorationDial\"",
        "id=\"mobileRestorationDial\"",
        "function renderGreenhouseRestorationDial",
        "function greenhouseDialPhase",
        "data-restoration-goal",
        "--dial-pct",
        "function pulseActiveGreenhouseIntake()",
        "body.greenhouse-intake .greenhouse-revival-light",
        "body.greenhouse-intake .greenhouse-restoration-dial",
        "pulseActiveGreenhouseIntake();",
        "mobile-greenhouse-plinth",
        "mobilePlinth.dataset.stageLabel = stage.shortLabel",
        "body[data-active-greenhouse-stage=\"moonlit\"]",
        "body[data-active-greenhouse-stage=\"bloodroot\"]",
        "@keyframes greenhouse-mist-drift",
        "@media (prefers-reduced-motion: reduce)",
        "body.round-one-active.round-one-complete .objective",
        "body.round-one-active.round-one-complete .active-greenhouse-stage",
        "body.round-one-active.round-one-complete .left",
        "body.round-one-active.round-one-complete .bouquet-bind-seal",
        "body.round-one-active.round-one-complete .ritual-log { display:none; }",
        "let coins = 0",
        "function completionCoinPayout",
        "function focusedSliceCompletionMessage",
        "function focusedPayoffCeremony()",
        "function renderFocusedPayoffCeremony(ceremony)",
        "payoff-transaction",
        "id=\"payoffTransaction\"",
        "First Bouquet Complete",
        "Greenhouse Restored",
        "Moonlit Wreath Complete",
        "Bloodroot Compact Complete",
        "+${roundOnePlan.reward.coins} coins ->",
        "+${roundTwoPlan.reward.coins} coins ->",
        "+${roundThreePlan.reward.coins} coins ->",
        "panel.dataset.payoffPrimary = ceremony.primary",
        "$(\"restoreGreenhouseBtn\").hidden = ceremony.primary !== \"spend\"",
        "$(\"nextOrderBtn\").hidden = ceremony.primary !== \"next\"",
        "roundComplete && focusedSliceRound(plan)",
        "MOONLIT_GREENHOUSE_UPGRADE_COST",
        "let roundTwoGreenhouseUpgraded = false",
        "round-two-upgrade-pending",
        "function upgradeRoundTwoGreenhouse()",
        "function advanceGreenhouseUpgrade()",
        "Upgrade Greenhouse · ${MOONLIT_GREENHOUSE_UPGRADE_COST} coins",
        "Upgrade the greenhouse.",
        "currentRound === 2 && roundComplete && roundOneRestored && !roundTwoGreenhouseUpgraded",
        "roundTwoGreenhouseUpgraded = Boolean(state.roundTwoGreenhouseUpgraded || currentRound > 2)",
        "body.round-two-upgrade-pending .round-one-restoration",
        "round-two-upgrade-complete",
        "focused-slice-failed",
        "body.focused-slice-failed #renewBtn.visible",
        "second-greenhouse-upgrade",
        "MOONLIT GREENHOUSE UPGRADED",
        "Next Order → Bloodroot Compact",
        "FINAL ORDER",
        "round-three-final-pending",
        "round-three-final-complete",
        "third-greenhouse-finale",
        "BLOODROOT CONSERVATORY RAISED",
        "Play Again → First Bouquet",
        "function replayFocusedSlice",
        "currentRound === 3 && roundComplete",
        "restoration-xp-preview",
        "body.round-one-active.round-one-complete .greenhouse-payoff-ladder",
        "body.round-two-upgrade-pending .restoration-xp-preview",
        "body.round-two-upgrade-pending .greenhouse-payoff-ladder",
        "body.round-one-active.round-one-complete #bouquetStreakBadge",
        "body.round-one-active.round-one-complete #nextStreakTargetBadge",
        "body.round-two-upgrade-complete #bouquetStreakBadge",
        "body.round-two-upgrade-complete #nextStreakTargetBadge",
        "function restorationGreenhouseXpPreview",
        "Greenhouse +180 XP",
        "greenhouse-payoff-fill",
        "Restore Greenhouse · 100 coins",
        "function restoreRoundOneGreenhouse",
        "nextOrderBtn",
        "Next Order →",
        "roundOneRestored",
        "next-order-cue",
        "Restored Greenhouse - Moonlit Wreath begins",
        "restored-greenhouse-handoff",
        "restored-next-order-focus",
        "restored-next-order-guide",
        "restored-greenhouse-status",
        "function renderRestoredGreenhouseStatus",
        "Moonlit Greenhouse",
        "Bloodroot Conservatory",
        "Moonlit order under glass.",
        "Bloodroot under crimson glass.",
        "const failedFocusedRestoredOrder = roundOneRestored",
        "isRestoredRoundTwoWindow() || failedFocusedRestoredOrder",
        "function isRestoredNextOrderFocus",
        "return isRestoredRoundTwoWindow()",
        "if (!isRestoredRoundTwoWindow())",
        "body.restored-next-order-focus .controls",
        "body.restored-next-order-focus.restored-next-order-guide:not(.restored-greenhouse-handoff):not(.first-move-made) .first-swap-cue",
        "isRestoredRoundTwoGuideActive()",
        "@media (min-width: 761px) and (max-height: 820px)",
        "grid-template-columns: 330px minmax(0, 1fr);",
        "width: min(650px, calc(100vh - 186px), calc(100vw - 470px));",
        "width: min(620px, calc(100vh - 262px), calc(100vw - 470px));",
        "height: calc(100vh - 26px);",
        "body.round-one-active .bottom { display: none !important; }",
        "body.restored-next-order-focus .restored-greenhouse-meter { display:none; }",
        "body.restored-greenhouse-handoff .left { display:block!important; }",
        "font-size: 50px;",
        "font-size: 18px;",
        "width: 38px;",
        "body.restored-greenhouse-handoff .controls",
        "function startRestoredGreenhouseHandoff",
        "function focusRestoredNextOrderViewport",
        "window.scrollTo({ top: 0, behavior: \"auto\" })",
        "<strong>Moonlit Wreath:</strong> Match beside the glowing Cursed Thorns.",
        "Bouquet Streak",
        "bouquetStreak",
        "bouquetStreakBadge",
        "nextStreakTargetBadge",
        "Next Streak Target",
        "function nextStreakTargetMarkup",
        "STREAK_COIN_BONUS_STEP",
        "STREAK_COIN_BONUS_CAP",
        "function bouquetStreakBonusPercent",
        "function bouquetStreakPayout",
        "function validBouquetStreak",
        "Choose Your Reward",
        "rewardChoicePanel",
        "rewardChoiceState",
        "reward-choice-value",
        "reward-choice-claim",
        "Greenhouse Cuttings",
        "Apothecary Kit",
        "Black Market Favor",
        "function choosePostBouquetReward",
        "function applyDefaultRewardChoice",
        "function validRewardChoiceState",
        "data-reward-choice=\"greenhouse\"",
        "data-reward-choice=\"apothecary\"",
        "data-reward-choice=\"blackMarket\"",
        "Flowerpedia",
        "Flowerpedia unlocked",
        "flowerpediaEntries",
        "flowerpediaLedger",
        "flowerpediaModal",
        "flowerpediaUnlocked",
        "flowerpediaUnlocks",
        "Velvet Funeral",
        "Cursed Thorn Field Note",
        "function unlockFlowerpediaEntry",
        "function renderFlowerpediaLedger",
        "function renderFlowerpediaEntries",
        "function validFlowerpediaUnlocks",
        "FLOWERPEDIA_FIRST_BOUQUET_ID",
        "FLOWERPEDIA_THORN_NOTE_ID",
        "Chapter 1: Midnight Conservatory",
        "Glasshouse Atrium",
        "chapterProgress",
        "chapterOneProgress",
        "chapterRewardsClaimed",
        "chapterRewards",
        "Chapter 1 reward claimed",
        "function maybeClaimChapterOneReward",
        "function renderChapterOneProgress",
        "function chapterOneModalMarkup",
        "function validChapterRewardsClaimed",
        "CHAPTER_ONE_REWARD_ID",
        "The Bouquet Withered",
        "Retry Bouquet",
        "failedBouquetGoals",
        "retryBouquetPrompt",
        "function isBouquetFailed",
        "function failedBouquetCopy",
        "function failedBouquetRitualMessage",
        "function markBouquetFailed",
        "function remainingObjectiveRows",
        "function roundObjectivesComplete",
        "Bouquet Path",
        "bouquetPath",
        "bouquet-path-nodes",
        "data-bouquet-state=\"complete\"",
        "data-bouquet-state=\"current\"",
        "data-bouquet-state=\"locked\"",
        "data-bouquet-state=\"withered\"",
        "function renderBouquetPath",
        "function bouquetPathRoundNumbers",
        "function bouquetPathNodeMarkup",
        "function bouquetPathState",
        "Round 3 Focus",
        "roundThreeFocus",
        "Bloodroot Compact payoff",
        "data-round-three-state=\"tease\"",
        "data-round-three-state=\"next\"",
        "data-round-three-state=\"current\"",
        "data-round-three-state=\"withered\"",
        "data-round-three-state=\"complete\"",
        "function renderRoundThreeFocus",
        "function roundThreeFocusState",
        "function roundThreeFocusCopy",
        "function roundThreePayoffCopy",
        "Round 4 Contract",
        "roundFourPreview",
        "Saint's Night Ledger payoff",
        "Solar Ash",
        "data-round-four-state=\"tease\"",
        "data-round-four-state=\"next\"",
        "data-round-four-state=\"current\"",
        "data-round-four-state=\"withered\"",
        "data-round-four-state=\"complete\"",
        "function renderRoundFourPreview",
        "function roundFourPreviewState",
        "function roundFourPreviewCopy",
        "function roundFourPayoffCopy",
        "Round 5 Grand Bouquet",
        "roundFivePreview",
        "Sub Rosa Grand Bouquet payoff",
        "Play Again → First Bouquet",
        "data-round-five-state=\"tease\"",
        "data-round-five-state=\"next\"",
        "data-round-five-state=\"current\"",
        "data-round-five-state=\"withered\"",
        "data-round-five-state=\"complete\"",
        "function renderRoundFivePreview",
        "function roundFivePreviewState",
        "function roundFivePreviewCopy",
        "function roundFivePayoffCopy",
        "Round 6 Encore Loop",
        "roundSixPreview",
        "First Bouquet 2",
        "Round 6 encore payoff",
        "data-round-six-state=\"tease\"",
        "data-round-six-state=\"next\"",
        "data-round-six-state=\"current\"",
        "data-round-six-state=\"withered\"",
        "data-round-six-state=\"complete\"",
        "function renderRoundSixPreview",
        "function roundSixPreviewState",
        "function roundSixPreviewCopy",
        "function roundSixPayoffCopy",
        "Round 7 Thorn Encore",
        "roundSevenPreview",
        "Moonlit Wreath 2",
        "Round 7 encore Cursed Thorn payoff",
        "data-round-seven-state=\"tease\"",
        "data-round-seven-state=\"next\"",
        "data-round-seven-state=\"current\"",
        "data-round-seven-state=\"withered\"",
        "data-round-seven-state=\"complete\"",
        "function renderRoundSevenPreview",
        "function roundSevenPreviewState",
        "function roundSevenPreviewCopy",
        "function roundSevenPayoffCopy",
        "Round 8 Bloodroot Encore",
        "roundEightPreview",
        "Bloodroot Compact 2",
        "Round 8 encore Bloodroot Compact payoff",
        "data-round-eight-state=\"tease\"",
        "data-round-eight-state=\"next\"",
        "data-round-eight-state=\"current\"",
        "data-round-eight-state=\"withered\"",
        "data-round-eight-state=\"complete\"",
        "function renderRoundEightPreview",
        "function roundEightPreviewState",
        "function roundEightPreviewCopy",
        "function roundEightPayoffCopy",
        "Round 9 Ledger Encore",
        "roundNinePreview",
        "Saint's Night Ledger 2",
        "Round 9 encore Saint's Night Ledger payoff",
        "data-round-nine-state=\"tease\"",
        "data-round-nine-state=\"next\"",
        "data-round-nine-state=\"current\"",
        "data-round-nine-state=\"withered\"",
        "data-round-nine-state=\"complete\"",
        "function renderRoundNinePreview",
        "function roundNinePreviewState",
        "function roundNinePreviewCopy",
        "function roundNinePayoffCopy",
        "Round 10 Grand Encore",
        "roundTenPreview",
        "Sub Rosa Grand Bouquet 2",
        "Round 10 encore Sub Rosa Grand Bouquet payoff",
        "data-round-ten-state=\"tease\"",
        "data-round-ten-state=\"next\"",
        "data-round-ten-state=\"current\"",
        "data-round-ten-state=\"withered\"",
        "data-round-ten-state=\"complete\"",
        "function renderRoundTenPreview",
        "function roundTenPreviewState",
        "function roundTenPreviewCopy",
        "function roundTenPayoffCopy",
        "Round 11 First Bouquet Encore",
        "roundElevenPreview",
        "First Bouquet 3",
        "Round 11 encore First Bouquet payoff",
        "data-round-eleven-state=\"tease\"",
        "data-round-eleven-state=\"next\"",
        "data-round-eleven-state=\"current\"",
        "data-round-eleven-state=\"withered\"",
        "data-round-eleven-state=\"complete\"",
        "function renderRoundElevenPreview",
        "function roundElevenPreviewState",
        "function roundElevenPreviewCopy",
        "function roundElevenPayoffCopy",
        "Round 12 Moonlit Wreath Encore",
        "roundTwelvePreview",
        "Moonlit Wreath 3",
        "Round 12 encore Moonlit Wreath payoff",
        "data-round-twelve-state=\"tease\"",
        "data-round-twelve-state=\"next\"",
        "data-round-twelve-state=\"current\"",
        "data-round-twelve-state=\"withered\"",
        "data-round-twelve-state=\"complete\"",
        "function renderRoundTwelvePreview",
        "function roundTwelvePreviewState",
        "function roundTwelvePreviewCopy",
        "function roundTwelvePayoffCopy",
        "Round 13 Bloodroot Compact Encore",
        "roundThirteenPreview",
        "Bloodroot Compact 3",
        "Round 13 encore Bloodroot Compact payoff",
        "data-round-thirteen-state=\"tease\"",
        "data-round-thirteen-state=\"next\"",
        "data-round-thirteen-state=\"current\"",
        "data-round-thirteen-state=\"withered\"",
        "data-round-thirteen-state=\"complete\"",
        "function renderRoundThirteenPreview",
        "function roundThirteenPreviewState",
        "function roundThirteenPreviewCopy",
        "function roundThirteenPayoffCopy",
        "Round 14 Saint's Night Ledger Encore",
        "roundFourteenPreview",
        "Saint's Night Ledger 3",
        "Round 14 encore Saint's Night Ledger payoff",
        "data-round-fourteen-state=\"tease\"",
        "data-round-fourteen-state=\"next\"",
        "data-round-fourteen-state=\"current\"",
        "data-round-fourteen-state=\"withered\"",
        "data-round-fourteen-state=\"complete\"",
        "function renderRoundFourteenPreview",
        "function roundFourteenPreviewState",
        "function roundFourteenPreviewCopy",
        "function roundFourteenPayoffCopy",
        "Round 15 Sub Rosa Grand Bouquet Encore",
        "roundFifteenPreview",
        "Sub Rosa Grand Bouquet 3",
        "Round 15 encore Sub Rosa Grand Bouquet payoff",
        "data-round-fifteen-state=\"tease\"",
        "data-round-fifteen-state=\"next\"",
        "data-round-fifteen-state=\"current\"",
        "data-round-fifteen-state=\"withered\"",
        "data-round-fifteen-state=\"complete\"",
        "function renderRoundFifteenPreview",
        "function roundFifteenPreviewState",
        "function roundFifteenPreviewCopy",
        "function roundFifteenPayoffCopy",
        "Round 16 First Bouquet Encore",
        "roundSixteenPreview",
        "First Bouquet 4",
        "Round 16 encore First Bouquet payoff",
        "data-round-sixteen-state=\"tease\"",
        "data-round-sixteen-state=\"next\"",
        "data-round-sixteen-state=\"current\"",
        "data-round-sixteen-state=\"withered\"",
        "data-round-sixteen-state=\"complete\"",
        "function renderRoundSixteenPreview",
        "function roundSixteenPreviewState",
        "function roundSixteenPreviewCopy",
        "function roundSixteenPayoffCopy",
        "Round 17 Moonlit Wreath Encore",
        "roundSeventeenPreview",
        "Moonlit Wreath 4",
        "Round 17 encore Moonlit Wreath payoff",
        "data-round-seventeen-state=\"tease\"",
        "data-round-seventeen-state=\"next\"",
        "data-round-seventeen-state=\"current\"",
        "data-round-seventeen-state=\"withered\"",
        "data-round-seventeen-state=\"complete\"",
        "function renderRoundSeventeenPreview",
        "function roundSeventeenPreviewState",
        "function roundSeventeenPreviewCopy",
        "function roundSeventeenPayoffCopy",
        "Round 18 Bloodroot Compact Encore",
        "roundEighteenPreview",
        "Bloodroot Compact 4",
        "Round 18 encore Bloodroot Compact payoff",
        "data-round-eighteen-state=\"tease\"",
        "data-round-eighteen-state=\"next\"",
        "data-round-eighteen-state=\"current\"",
        "data-round-eighteen-state=\"withered\"",
        "data-round-eighteen-state=\"complete\"",
        "function renderRoundEighteenPreview",
        "function roundEighteenPreviewState",
        "function roundEighteenPreviewCopy",
        "function roundEighteenPayoffCopy",
        "Round 19 Saint's Night Ledger Encore",
        "roundNineteenPreview",
        "Saint's Night Ledger 4",
        "Round 19 encore Saint's Night Ledger payoff",
        "data-round-nineteen-state=\"tease\"",
        "data-round-nineteen-state=\"next\"",
        "data-round-nineteen-state=\"current\"",
        "data-round-nineteen-state=\"withered\"",
        "data-round-nineteen-state=\"complete\"",
        "function renderRoundNineteenPreview",
        "function roundNineteenPreviewState",
        "function roundNineteenPreviewCopy",
        "function roundNineteenPayoffCopy",
        "Round 20 Sub Rosa Grand Bouquet Encore",
        "roundTwentyPreview",
        "Sub Rosa Grand Bouquet 4",
        "Round 20 encore Sub Rosa Grand Bouquet payoff",
        "data-round-twenty-state=\"tease\"",
        "data-round-twenty-state=\"next\"",
        "data-round-twenty-state=\"current\"",
        "data-round-twenty-state=\"withered\"",
        "data-round-twenty-state=\"complete\"",
        "function renderRoundTwentyPreview",
        "function roundTwentyPreviewState",
        "function roundTwentyPreviewCopy",
        "function roundTwentyPayoffCopy",
        "Round 21 First Bouquet Encore",
        "roundTwentyOnePreview",
        "First Bouquet 5",
        "Round 21 encore First Bouquet payoff",
        "data-round-twenty-one-state=\"tease\"",
        "data-round-twenty-one-state=\"next\"",
        "data-round-twenty-one-state=\"current\"",
        "data-round-twenty-one-state=\"withered\"",
        "data-round-twenty-one-state=\"complete\"",
        "function renderRoundTwentyOnePreview",
        "function roundTwentyOnePreviewState",
        "function roundTwentyOnePreviewCopy",
        "function roundTwentyOnePayoffCopy",
        "Round 22 Moonlit Wreath Encore",
        "roundTwentyTwoPreview",
        "Moonlit Wreath 5",
        "Round 22 encore Moonlit Wreath payoff",
        "data-round-twenty-two-state=\"tease\"",
        "data-round-twenty-two-state=\"next\"",
        "data-round-twenty-two-state=\"current\"",
        "data-round-twenty-two-state=\"withered\"",
        "data-round-twenty-two-state=\"complete\"",
        "function renderRoundTwentyTwoPreview",
        "function roundTwentyTwoPreviewState",
        "function roundTwentyTwoPreviewCopy",
        "function roundTwentyTwoPayoffCopy",
        "Round 23 Bloodroot Compact Encore",
        "roundTwentyThreePreview",
        "Bloodroot Compact 5",
        "Round 23 encore Bloodroot Compact payoff",
        "data-round-twenty-three-state=\"tease\"",
        "data-round-twenty-three-state=\"next\"",
        "data-round-twenty-three-state=\"current\"",
        "data-round-twenty-three-state=\"withered\"",
        "data-round-twenty-three-state=\"complete\"",
        "function renderRoundTwentyThreePreview",
        "function roundTwentyThreePreviewState",
        "function roundTwentyThreePreviewCopy",
        "function roundTwentyThreePayoffCopy",
        "Round 24 Saint's Night Ledger Encore",
        "roundTwentyFourPreview",
        "Saint's Night Ledger 5",
        "Round 24 encore Saint's Night Ledger payoff",
        "data-round-twenty-four-state=\"tease\"",
        "data-round-twenty-four-state=\"next\"",
        "data-round-twenty-four-state=\"current\"",
        "data-round-twenty-four-state=\"withered\"",
        "data-round-twenty-four-state=\"complete\"",
        "function renderRoundTwentyFourPreview",
        "function roundTwentyFourPreviewState",
        "function roundTwentyFourPreviewCopy",
        "function roundTwentyFourPayoffCopy",
        "Round 25 Sub Rosa Grand Bouquet Encore",
        "roundTwentyFivePreview",
        "Sub Rosa Grand Bouquet 5",
        "Round 25 encore Sub Rosa Grand Bouquet payoff",
        "data-round-twenty-five-state=\"tease\"",
        "data-round-twenty-five-state=\"next\"",
        "data-round-twenty-five-state=\"current\"",
        "data-round-twenty-five-state=\"withered\"",
        "data-round-twenty-five-state=\"complete\"",
        "function renderRoundTwentyFivePreview",
        "function roundTwentyFivePreviewState",
        "function roundTwentyFivePreviewCopy",
        "function roundTwentyFivePayoffCopy",
        "Round 26 First Bouquet Encore",
        "roundTwentySixPreview",
        "First Bouquet 6",
        "Round 26 encore First Bouquet payoff",
        "data-round-twenty-six-state=\"tease\"",
        "data-round-twenty-six-state=\"next\"",
        "data-round-twenty-six-state=\"current\"",
        "data-round-twenty-six-state=\"withered\"",
        "data-round-twenty-six-state=\"complete\"",
        "function renderRoundTwentySixPreview",
        "function roundTwentySixPreviewState",
        "function roundTwentySixPreviewCopy",
        "function roundTwentySixPayoffCopy",
        "Round 27 Moonlit Wreath Encore",
        "roundTwentySevenPreview",
        "Moonlit Wreath 6",
        "Round 27 encore Moonlit Wreath payoff",
        "data-round-twenty-seven-state=\"tease\"",
        "data-round-twenty-seven-state=\"next\"",
        "data-round-twenty-seven-state=\"current\"",
        "data-round-twenty-seven-state=\"withered\"",
        "data-round-twenty-seven-state=\"complete\"",
        "function renderRoundTwentySevenPreview",
        "function roundTwentySevenPreviewState",
        "function roundTwentySevenPreviewCopy",
        "function roundTwentySevenPayoffCopy",
        "Round 28 Bloodroot Compact Encore",
        "roundTwentyEightPreview",
        "Bloodroot Compact 6",
        "Round 28 encore Bloodroot Compact payoff",
        "data-round-twenty-eight-state=\"tease\"",
        "data-round-twenty-eight-state=\"next\"",
        "data-round-twenty-eight-state=\"current\"",
        "data-round-twenty-eight-state=\"withered\"",
        "data-round-twenty-eight-state=\"complete\"",
        "function renderRoundTwentyEightPreview",
        "function roundTwentyEightPreviewState",
        "function roundTwentyEightPreviewCopy",
        "function roundTwentyEightPayoffCopy",
        "Round 29 Saint's Night Ledger Encore",
        "roundTwentyNinePreview",
        "Saint's Night Ledger 6",
        "Round 29 encore Saint's Night Ledger payoff",
        "data-round-twenty-nine-state=\"tease\"",
        "data-round-twenty-nine-state=\"next\"",
        "data-round-twenty-nine-state=\"current\"",
        "data-round-twenty-nine-state=\"withered\"",
        "data-round-twenty-nine-state=\"complete\"",
        "function renderRoundTwentyNinePreview",
        "function roundTwentyNinePreviewState",
        "function roundTwentyNinePreviewCopy",
        "function roundTwentyNinePayoffCopy",
        "Round 30 Sub Rosa Grand Bouquet Encore",
        "roundThirtyPreview",
        "Sub Rosa Grand Bouquet 6",
        "Round 30 encore Sub Rosa Grand Bouquet payoff",
        "data-round-thirty-state=\"tease\"",
        "data-round-thirty-state=\"next\"",
        "data-round-thirty-state=\"current\"",
        "data-round-thirty-state=\"withered\"",
        "data-round-thirty-state=\"complete\"",
        "function renderRoundThirtyPreview",
        "function roundThirtyPreviewState",
        "function roundThirtyPreviewCopy",
        "function roundThirtyPayoffCopy",
        "Round 31 First Bouquet Encore",
        "roundThirtyOnePreview",
        "First Bouquet 7",
        "Round 31 encore First Bouquet payoff",
        "data-round-thirty-one-state=\"tease\"",
        "data-round-thirty-one-state=\"next\"",
        "data-round-thirty-one-state=\"current\"",
        "data-round-thirty-one-state=\"withered\"",
        "data-round-thirty-one-state=\"complete\"",
        "function renderRoundThirtyOnePreview",
        "function roundThirtyOnePreviewState",
        "function roundThirtyOnePreviewCopy",
        "function roundThirtyOnePayoffCopy",
        "Round 32 Moonlit Wreath Encore",
        "roundThirtyTwoPreview",
        "Moonlit Wreath 7",
        "Round 32 encore Moonlit Wreath payoff",
        "data-round-thirty-two-state=\"tease\"",
        "data-round-thirty-two-state=\"next\"",
        "data-round-thirty-two-state=\"current\"",
        "data-round-thirty-two-state=\"withered\"",
        "data-round-thirty-two-state=\"complete\"",
        "function renderRoundThirtyTwoPreview",
        "function roundThirtyTwoPreviewState",
        "function roundThirtyTwoPreviewCopy",
        "function roundThirtyTwoPayoffCopy",
        "Round 33 Bloodroot Compact Encore",
        "roundThirtyThreePreview",
        "Bloodroot Compact 7",
        "Round 33 encore Bloodroot Compact payoff",
        "data-round-thirty-three-state=\"tease\"",
        "data-round-thirty-three-state=\"next\"",
        "data-round-thirty-three-state=\"current\"",
        "data-round-thirty-three-state=\"withered\"",
        "data-round-thirty-three-state=\"complete\"",
        "function renderRoundThirtyThreePreview",
        "function roundThirtyThreePreviewState",
        "function roundThirtyThreePreviewCopy",
        "function roundThirtyThreePayoffCopy",
        "Round 34 Saint's Night Ledger Encore",
        "roundThirtyFourPreview",
        "Saint's Night Ledger 7",
        "Round 34 encore Saint's Night Ledger payoff",
        "data-round-thirty-four-state=\"tease\"",
        "data-round-thirty-four-state=\"next\"",
        "data-round-thirty-four-state=\"current\"",
        "data-round-thirty-four-state=\"withered\"",
        "data-round-thirty-four-state=\"complete\"",
        "function renderRoundThirtyFourPreview",
        "function roundThirtyFourPreviewState",
        "function roundThirtyFourPreviewCopy",
        "function roundThirtyFourPayoffCopy",
        "Round 35 Sub Rosa Grand Bouquet Encore",
        "roundThirtyFivePreview",
        "Sub Rosa Grand Bouquet 7",
        "Round 35 encore Sub Rosa Grand Bouquet payoff",
        "data-round-thirty-five-state=\"tease\"",
        "data-round-thirty-five-state=\"next\"",
        "data-round-thirty-five-state=\"current\"",
        "data-round-thirty-five-state=\"withered\"",
        "data-round-thirty-five-state=\"complete\"",
        "function renderRoundThirtyFivePreview",
        "function roundThirtyFivePreviewState",
        "function roundThirtyFivePreviewCopy",
        "function roundThirtyFivePayoffCopy",
        "Round 36 First Bouquet Encore",
        "roundThirtySixPreview",
        "First Bouquet 8",
        "Round 36 encore First Bouquet payoff",
        "data-round-thirty-six-state=\"tease\"",
        "data-round-thirty-six-state=\"next\"",
        "data-round-thirty-six-state=\"current\"",
        "data-round-thirty-six-state=\"withered\"",
        "data-round-thirty-six-state=\"complete\"",
        "function renderRoundThirtySixPreview",
        "function roundThirtySixPreviewState",
        "function roundThirtySixPreviewCopy",
        "function roundThirtySixPayoffCopy",
        "Round 37 Moonlit Wreath Encore",
        "roundThirtySevenPreview",
        "Moonlit Wreath 8",
        "Round 37 encore Moonlit Wreath payoff",
        "data-round-thirty-seven-state=\"tease\"",
        "data-round-thirty-seven-state=\"next\"",
        "data-round-thirty-seven-state=\"current\"",
        "data-round-thirty-seven-state=\"withered\"",
        "data-round-thirty-seven-state=\"complete\"",
        "function renderRoundThirtySevenPreview",
        "function roundThirtySevenPreviewState",
        "function roundThirtySevenPreviewCopy",
        "function roundThirtySevenPayoffCopy",
        "Round 38 Bloodroot Compact Encore",
        "roundThirtyEightPreview",
        "Bloodroot Compact 8",
        "Round 38 encore Bloodroot Compact payoff",
        "data-round-thirty-eight-state=\"tease\"",
        "data-round-thirty-eight-state=\"next\"",
        "data-round-thirty-eight-state=\"current\"",
        "data-round-thirty-eight-state=\"withered\"",
        "data-round-thirty-eight-state=\"complete\"",
        "function renderRoundThirtyEightPreview",
        "function roundThirtyEightPreviewState",
        "function roundThirtyEightPreviewCopy",
        "function roundThirtyEightPayoffCopy",
        "Round 39 Saint's Night Ledger Encore",
        "roundThirtyNinePreview",
        "Saint's Night Ledger 8",
        "Round 39 encore Saint's Night Ledger payoff",
        "data-round-thirty-nine-state=\"tease\"",
        "data-round-thirty-nine-state=\"next\"",
        "data-round-thirty-nine-state=\"current\"",
        "data-round-thirty-nine-state=\"withered\"",
        "data-round-thirty-nine-state=\"complete\"",
        "function renderRoundThirtyNinePreview",
        "function roundThirtyNinePreviewState",
        "function roundThirtyNinePreviewCopy",
        "function roundThirtyNinePayoffCopy",
        "Round 40 Sub Rosa Grand Bouquet Encore",
        "roundFortyPreview",
        "Sub Rosa Grand Bouquet 8",
        "Round 40 encore Sub Rosa Grand Bouquet payoff",
        "data-round-forty-state=\"tease\"",
        "data-round-forty-state=\"next\"",
        "data-round-forty-state=\"current\"",
        "data-round-forty-state=\"withered\"",
        "data-round-forty-state=\"complete\"",
        "function renderRoundFortyPreview",
        "function roundFortyPreviewState",
        "function roundFortyPreviewCopy",
        "function roundFortyPayoffCopy",
        "Round 41 First Bouquet Encore",
        "roundFortyOnePreview",
        "First Bouquet 9",
        "Round 41 encore First Bouquet payoff",
        "data-round-forty-one-state=\"tease\"",
        "data-round-forty-one-state=\"next\"",
        "data-round-forty-one-state=\"current\"",
        "data-round-forty-one-state=\"withered\"",
        "data-round-forty-one-state=\"complete\"",
        "function renderRoundFortyOnePreview",
        "function roundFortyOnePreviewState",
        "function roundFortyOnePreviewCopy",
        "function roundFortyOnePayoffCopy",
        "Round 42 Moonlit Wreath Encore",
        "roundFortyTwoPreview",
        "Moonlit Wreath 9",
        "Round 42 encore Moonlit Wreath payoff",
        "data-round-forty-two-state=\"tease\"",
        "data-round-forty-two-state=\"next\"",
        "data-round-forty-two-state=\"current\"",
        "data-round-forty-two-state=\"withered\"",
        "data-round-forty-two-state=\"complete\"",
        "function renderRoundFortyTwoPreview",
        "function roundFortyTwoPreviewState",
        "function roundFortyTwoPreviewCopy",
        "function roundFortyTwoPayoffCopy",
        "Round 43 Bloodroot Compact Encore",
        "roundFortyThreePreview",
        "Bloodroot Compact 9",
        "Round 43 encore Bloodroot Compact payoff",
        "data-round-forty-three-state=\"tease\"",
        "data-round-forty-three-state=\"next\"",
        "data-round-forty-three-state=\"current\"",
        "data-round-forty-three-state=\"withered\"",
        "data-round-forty-three-state=\"complete\"",
        "function renderRoundFortyThreePreview",
        "function roundFortyThreePreviewState",
        "function roundFortyThreePreviewCopy",
        "function roundFortyThreePayoffCopy",
        "Round 44 Saint's Night Ledger Encore",
        "roundFortyFourPreview",
        "Saint's Night Ledger 9",
        "Round 44 encore Saint's Night Ledger payoff",
        "data-round-forty-four-state=\"tease\"",
        "data-round-forty-four-state=\"next\"",
        "data-round-forty-four-state=\"current\"",
        "data-round-forty-four-state=\"withered\"",
        "data-round-forty-four-state=\"complete\"",
        "function renderRoundFortyFourPreview",
        "function roundFortyFourPreviewState",
        "function roundFortyFourPreviewCopy",
        "function roundFortyFourPayoffCopy",
        "Round 45 Sub Rosa Grand Bouquet Encore",
        "roundFortyFivePreview",
        "Sub Rosa Grand Bouquet 9",
        "Round 45 encore Sub Rosa Grand Bouquet payoff",
        "data-round-forty-five-state=\"tease\"",
        "data-round-forty-five-state=\"next\"",
        "data-round-forty-five-state=\"current\"",
        "data-round-forty-five-state=\"withered\"",
        "data-round-forty-five-state=\"complete\"",
        "function renderRoundFortyFivePreview",
        "function roundFortyFivePreviewState",
        "function roundFortyFivePreviewCopy",
        "function roundFortyFivePayoffCopy",
        "Round 46 First Bouquet Encore",
        "roundFortySixPreview",
        "First Bouquet 10",
        "Round 46 encore First Bouquet payoff",
        "data-round-forty-six-state=\"tease\"",
        "data-round-forty-six-state=\"next\"",
        "data-round-forty-six-state=\"current\"",
        "data-round-forty-six-state=\"withered\"",
        "data-round-forty-six-state=\"complete\"",
        "function renderRoundFortySixPreview",
        "function roundFortySixPreviewState",
        "function roundFortySixPreviewCopy",
        "function roundFortySixPayoffCopy",
        "Round 47 Moonlit Wreath Encore",
        "roundFortySevenPreview",
        "Moonlit Wreath 10",
        "Round 47 encore Moonlit Wreath payoff",
        "data-round-forty-seven-state=\"tease\"",
        "data-round-forty-seven-state=\"next\"",
        "data-round-forty-seven-state=\"current\"",
        "data-round-forty-seven-state=\"withered\"",
        "data-round-forty-seven-state=\"complete\"",
        "function renderRoundFortySevenPreview",
        "function roundFortySevenPreviewState",
        "function roundFortySevenPreviewCopy",
        "function roundFortySevenPayoffCopy",
        "Round 48 Bloodroot Compact Encore",
        "roundFortyEightPreview",
        "Bloodroot Compact 10",
        "Round 48 encore Bloodroot Compact payoff",
        "data-round-forty-eight-state=\"tease\"",
        "data-round-forty-eight-state=\"next\"",
        "data-round-forty-eight-state=\"current\"",
        "data-round-forty-eight-state=\"withered\"",
        "data-round-forty-eight-state=\"complete\"",
        "function renderRoundFortyEightPreview",
        "function roundFortyEightPreviewState",
        "function roundFortyEightPreviewCopy",
        "function roundFortyEightPayoffCopy",
        "Round 49 Saint's Night Ledger Encore",
        "roundFortyNinePreview",
        "Saint's Night Ledger 10",
        "Round 49 encore Saint's Night Ledger payoff",
        "data-round-forty-nine-state=\"tease\"",
        "data-round-forty-nine-state=\"next\"",
        "data-round-forty-nine-state=\"current\"",
        "data-round-forty-nine-state=\"withered\"",
        "data-round-forty-nine-state=\"complete\"",
        "function renderRoundFortyNinePreview",
        "function roundFortyNinePreviewState",
        "function roundFortyNinePreviewCopy",
        "function roundFortyNinePayoffCopy",
        "Round 50 Sub Rosa Grand Bouquet Encore",
        "roundFiftyPreview",
        "Sub Rosa Grand Bouquet 10",
        "Round 50 encore Sub Rosa Grand Bouquet payoff",
        "data-round-fifty-state=\"tease\"",
        "data-round-fifty-state=\"next\"",
        "data-round-fifty-state=\"current\"",
        "data-round-fifty-state=\"withered\"",
        "data-round-fifty-state=\"complete\"",
        "function renderRoundFiftyPreview",
        "function roundFiftyPreviewState",
        "function roundFiftyPreviewCopy",
        "function roundFiftyPayoffCopy",
        "Round 51 First Bouquet Encore",
        "roundFiftyOnePreview",
        "First Bouquet 11",
        "Round 51 encore First Bouquet payoff",
        "data-round-fifty-one-state=\"tease\"",
        "data-round-fifty-one-state=\"next\"",
        "data-round-fifty-one-state=\"current\"",
        "data-round-fifty-one-state=\"withered\"",
        "data-round-fifty-one-state=\"complete\"",
        "function renderRoundFiftyOnePreview",
        "function roundFiftyOnePreviewState",
        "function roundFiftyOnePreviewCopy",
        "function roundFiftyOnePayoffCopy",
        "Round 52 Moonlit Wreath Encore",
        "roundFiftyTwoPreview",
        "Moonlit Wreath 11",
        "Round 52 encore Moonlit Wreath payoff",
        "data-round-fifty-two-state=\"tease\"",
        "data-round-fifty-two-state=\"next\"",
        "data-round-fifty-two-state=\"current\"",
        "data-round-fifty-two-state=\"withered\"",
        "data-round-fifty-two-state=\"complete\"",
        "function renderRoundFiftyTwoPreview",
        "function roundFiftyTwoPreviewState",
        "function roundFiftyTwoPreviewCopy",
        "function roundFiftyTwoPayoffCopy",
        "Round 53 Bloodroot Compact Encore",
        "roundFiftyThreePreview",
        "Bloodroot Compact 11",
        "Round 53 encore Bloodroot Compact payoff",
        "data-round-fifty-three-state=\"tease\"",
        "data-round-fifty-three-state=\"next\"",
        "data-round-fifty-three-state=\"current\"",
        "data-round-fifty-three-state=\"withered\"",
        "data-round-fifty-three-state=\"complete\"",
        "function renderRoundFiftyThreePreview",
        "function roundFiftyThreePreviewState",
        "function roundFiftyThreePreviewCopy",
        "function roundFiftyThreePayoffCopy",
        "Round 54 Saint's Night Ledger Encore",
        "roundFiftyFourPreview",
        "Saint's Night Ledger 11",
        "Round 54 encore Saint's Night Ledger payoff",
        "data-round-fifty-four-state=\"tease\"",
        "data-round-fifty-four-state=\"next\"",
        "data-round-fifty-four-state=\"current\"",
        "data-round-fifty-four-state=\"withered\"",
        "data-round-fifty-four-state=\"complete\"",
        "function renderRoundFiftyFourPreview",
        "function roundFiftyFourPreviewState",
        "function roundFiftyFourPreviewCopy",
        "function roundFiftyFourPayoffCopy",
        "Round 55 Sub Rosa Grand Bouquet Encore",
        "roundFiftyFivePreview",
        "Sub Rosa Grand Bouquet 11",
        "Round 55 encore Sub Rosa Grand Bouquet payoff",
        "data-round-fifty-five-state=\"tease\"",
        "data-round-fifty-five-state=\"next\"",
        "data-round-fifty-five-state=\"current\"",
        "data-round-fifty-five-state=\"withered\"",
        "data-round-fifty-five-state=\"complete\"",
        "function renderRoundFiftyFivePreview",
        "function roundFiftyFivePreviewState",
        "function roundFiftyFivePreviewCopy",
        "function roundFiftyFivePayoffCopy",
        "Round 56 First Bouquet Encore",
        "roundFiftySixPreview",
        "First Bouquet 12",
        "Round 56 encore First Bouquet payoff",
        "data-round-fifty-six-state=\"tease\"",
        "data-round-fifty-six-state=\"next\"",
        "data-round-fifty-six-state=\"current\"",
        "data-round-fifty-six-state=\"withered\"",
        "data-round-fifty-six-state=\"complete\"",
        "function renderRoundFiftySixPreview",
        "function roundFiftySixPreviewState",
        "function roundFiftySixPreviewCopy",
        "function roundFiftySixPayoffCopy",
        "Round 57 Moonlit Wreath Encore",
        "roundFiftySevenPreview",
        "Moonlit Wreath 12",
        "Round 57 encore Moonlit Wreath payoff",
        "data-round-fifty-seven-state=\"tease\"",
        "data-round-fifty-seven-state=\"next\"",
        "data-round-fifty-seven-state=\"current\"",
        "data-round-fifty-seven-state=\"withered\"",
        "data-round-fifty-seven-state=\"complete\"",
        "function renderRoundFiftySevenPreview",
        "function roundFiftySevenPreviewState",
        "function roundFiftySevenPreviewCopy",
        "function roundFiftySevenPayoffCopy",
        "shapeBloomBtn",
        "Shape Bloom",
        "Black Candle Vine",
        "function lineRelicForMatch",
        "function queueLineRelicBurst",
        "function lineRelicMessage",
        "line4",
        "Eclipse Seed Rune",
        "function rareSeedRuneForMatch",
        "function queueRareSeedRuneBurst",
        "function rareSeedRuneMessage",
        "line5",
        "seed-rune",
        "Rune-Tended Soil",
        "function plantEclipseSeedRune",
        "data-action=\"plant-eclipse-seed-rune\"",
        "pendingRuneTendedSoil",
        "activeRuneTendedSoil",
        "Pruning Shears",
        "pruningShearsBtn",
        "pruningShearsCount",
        "boosterPanel",
        "function togglePruningShears",
        "function usePruningShears",
        "function queuePruningShearBurst",
        "shears-target",
        "boosters.pruningShears",
        "Moonwater Flask",
        "moonwaterFlaskBtn",
        "moonwaterFlaskCount",
        "function toggleMoonwaterFlask",
        "function useMoonwaterFlask",
        "function moonwaterPatchCells",
        "function shuffleMoonwaterPatch",
        "function queueMoonwaterBurst",
        "moonwater-target",
        "moonwater-area",
        "boosters.moonwaterFlask",
        "Black Candle",
        "blackCandleBtn",
        "blackCandleCount",
        "blackCandleModes",
        "blackCandleAxis",
        "function toggleBlackCandle",
        "function useBlackCandle",
        "function blackCandleLineCells",
        "function refillBlackCandleLine",
        "function queueBlackCandleBurst",
        "black-candle-line",
        "boosters.blackCandle",
        "Grave Soil",
        "graveSoilBtn",
        "graveSoilCount",
        "graveSoilCells",
        "function toggleGraveSoil",
        "function useGraveSoil",
        "function queueGraveSoilBurst",
        "function graveSoilRelicForMatch",
        "function isGraveSoilEligible",
        "grave-soil-target",
        "grave-soil-ready",
        "boosters.graveSoil",
        "activeBooster",
        "Cursed Thorn",
        "thornGoal",
        "cursed-thorn-overlay",
        "thorn-teach",
        "thorn-teach-lane",
        "thorn-teach-blocker",
        "thorn-teach-marker",
        "guided Cursed Thorn swap tile",
        "marked Cursed Thorn target",
        "Cursed Thorn match lane",
        "thornObjectiveHint",
        "Match beside Cursed Thorns",
        "Cursed Thorn lesson",
        "function seedRoundTwoThornTeachingMove",
        "function roundTwoThornTeachingSwap",
        "function hasRoundTwoThornTeachingMove",
        "function cellsTouchCursedThorn",
        "function damageAdjacentThorns",
        "function thornDamageMessage",
        "shapeDiscoveryHint",
        "L/T/cross = Shape Bloom",
        "function shapeDiscoveryHintMarkup",
        "function patternDiscoveryCopy",
        "vial-meter",
        "data-vial=\"SAP\"",
        "let moves = roundTemplates[0].moves",
        "event.key.toLowerCase() === \"n\"",
        "function seedCurrentTargetMoves",
        "writeTargetLegalMovePatch(4, 0, targetIds[1], 4)",
        "function writeTargetLegalMovePatch(originX, originY, flowerId, lineLength = 3)",
        "function seedRoundOneBlackCandleVineLesson",
        "function findTargetLegalMove",
        "function seedFocusedGuideMove",
        "function nextTargetMoveHint",
        "findTargetLegalMove(target.flowerId, targetIndex)",
        "Next Bouquet",
        "roundCeremony",
        "factionXpFill",
        "apothecary-fill",
        "assets/tiles/96/withered_sun_medallion.png",
        "assets/tiles/96/bone_white_thorn_star.png",
        "assets/tiles/96/purple_nightshade_bloom.png",
        "assets/tiles/96/bloodroot_ruby_shard.png",
        "assets/tiles/96/amber_resin_seed.png",
        "assets/tiles/96/crimson_rose_rune.png",
        "const flowerIcon48",
        "const flowerIconSrcset",
        "prepare_reference_flower_tiles.js",
    ]
    retired_required_patterns = [
        r'restoredGreenhouseStatus',
        r'restored-greenhouse',
        r'restoration-xp-preview',
        r'restorationGreenhouseXpPreview',
        r'greenhouse-payoff',
        r'greenhouse-upgrade-ladder',
        r'greenhouse-order-ladder',
        r'renderGreenhouseUpgradeLadders',
        r'renderRestoredGreenhouseStatus',
        r'Greenhouse \+\d+ XP',
        r'Moonlit order under glass',
        r'Bloodroot under crimson glass',
        r'data-reward-choice=',
        r'Bouquet Path',
        r'BouquetPath',
        r'bouquetPath',
        r'bouquet-path-',
        r'data-bouquet-state=',
        r'renderBouquetPath',
        r'roundThreeFocus',
        r'Round 3 Focus',
        r'Bloodroot Compact payoff',
        r'round[A-Z][A-Za-z]+Preview',
        r'Round (?:[4-9]|[1-5][0-9])\b',
        r'data-round-(?:three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty)',
        r'function renderRound[A-Z][A-Za-z]+',
        r'function round[A-Z][A-Za-z]+(?:Preview|Payoff|Focus)',
        r'Moonlit Wreath (?:[2-9]|1[0-2])',
        r'First Bouquet (?:[2-9]|1[0-2])',
        r'Bloodroot Compact (?:[2-9]|1[0-1])',
        r"Saint's Night Ledger",
        r'Sub Rosa Grand Bouquet',
    ]
    required = [
        needle for needle in required
        if not any(re.search(pattern, needle) for pattern in retired_required_patterns)
    ]
    required.extend([
        "id=\"bouquetProgress\"",
        "id=\"bouquetProgressLabel\"",
        "id=\"bouquetProgressNext\"",
        "function updateBouquetProgress",
        "Bouquet ${progress.earned}/${progress.needed} -> +${plan.reward.coins} coins",
        "function greenhouseNextUnlockLabel",
        "Restore First Bouquet Glass",
        "Unlock Bloodroot Compact",
        "Raise Bloodroot Conservatory",
        "id=\"tutorialPanel\"",
        "id=\"tutorialHelpBtn\"",
        "id=\"tutorialSkipBtn\"",
        "let tutorialSkipped = false",
        "function startTutorial({ replay = false } = {})",
        "function skipTutorial",
        "function scheduleFreshTutorial",
        "Swap the glowing flowers.",
        "Match 3 fills the bouquet.",
        "Match 4 makes Black Candle Vine.",
        "Match beside thorns.",
        "Moves ended. Retry the bouquet.",
        "Coins restore the greenhouse.",
        "body.tutorial-active.focused-slice-failed #renewBtn.visible",
        "document.body.dataset.tutorialPrompt = tutorialActive ? tutorialCopy() : \"\"",
        "const MAX_BOARD_PARTICLES = 56",
        "@media (prefers-reduced-motion: reduce)",
    ])
    missing = [needle for needle in required if needle not in html]
    if missing:
        raise SystemExit(f"Missing HTML match-shape hooks: {missing}")
    dormant_runtime_patterns = [
        r'id="bouquetPath"',
        r'id="pathLedgerDrawer"',
        r'id="roundThreeFocus"',
        r'id="round[A-Z][A-Za-z]+Preview"',
        r'^\s+renderBouquetPath\(\);$',
        r'^\s+renderRoundThreeFocus\(\);$',
        r'^\s+renderRound[A-Z][A-Za-z]+Preview\(\);$',
        r'function\s+renderBouquetPath\b',
        r'function\s+renderRoundThreeFocus\b',
        r'function\s+renderRound[A-Z][A-Za-z]+Preview\b',
        r'roundFourAuditMarkers',
        r'roundFiftySevenAuditMarkers',
        r'roundFiftySevenPreview',
        r'Moonlit Wreath 12',
    ]
    dormant_runtime_hits = [
        pattern
        for pattern in dormant_runtime_patterns
        if re.search(pattern, html, re.MULTILINE)
    ]
    if dormant_runtime_hits:
        raise SystemExit(
            "Dormant future UI returned to the active runtime: "
            f"{dormant_runtime_hits}"
        )
    forbidden = [
        'class="bouquet-stem-count"',
        'filter: "blur(2px) brightness(1.35)"',
        'class="restoration-ledger"',
        'id="restorationEarned"',
        'id="restorationSpent"',
        'id="restorationNext"',
        "First Bouquet Sealed · +120 coin reward",
        "Greenhouse Restored ·",
        "Moonlit Wreath Sealed · +${roundTwoPlan.reward.coins} coin reward",
        "Bloodroot Compact Sealed · +${roundThreePlan.reward.coins} coin reward",
        "Retry Bouquet preserves coins, XP, Flowerpedia, Chapter rewards, Chest Storage, and boosters.",
        'id="restoredGreenhouseStatus"',
        'id="greenhouseOrderLadder"',
        'id="greenhousePayoffLadder"',
        'id="restorationXpPreview"',
        'data-vial="MANA"',
        'data-vial="BLOOD"',
        "Greenhouse +180 XP",
    ]
    present_forbidden = [needle for needle in forbidden if needle in html]
    if present_forbidden:
        raise SystemExit(
            f"Forbidden HTML match-shape hooks returned: {present_forbidden}"
        )
    compositor_safe_restoration_keyframes = (
        "bouquet-trophy-awaken",
        "withered-glass-fall",
        "restored-glass-reveal",
        "restoration-light-bloom",
        "restoration-root-rise",
        "restoration-rays-open",
        "restoration-state-pop",
        "greenhouse-xp-confirm",
        "greenhouse-ladder-confirm",
    )
    restoration_keyframes = re.findall(
        r"@keyframes ([a-z-]+) \{(.*?)\n    \}",
        html,
        re.DOTALL,
    )
    unsafe_restoration_filters = [
        name
        for name, body in restoration_keyframes
        if name in compositor_safe_restoration_keyframes and "filter:" in body
    ]
    if unsafe_restoration_filters:
        raise SystemExit(
            "Restoration keyframes must remain compositor-safe: "
            f"{unsafe_restoration_filters}"
        )
    unsafe_restoration_transitions = [
        "transition:opacity 760ms ease,filter 760ms ease",
        "transition:opacity 760ms ease,filter 760ms ease,transform",
    ]
    present_unsafe_transitions = [
        needle for needle in unsafe_restoration_transitions if needle in html
    ]
    if present_unsafe_transitions:
        raise SystemExit(
            "Restoration reveal must not animate CSS filters: "
            f"{present_unsafe_transitions}"
        )
    missing_assets = [asset for asset in ALTAR_TILE_ASSETS if not (ROOT / asset).exists()]
    if missing_assets:
        raise SystemExit(f"Missing altar tile assets: {missing_assets}")
    board_socket = ROOT / "assets/board/occult_altar_socket.svg"
    if not board_socket.exists():
        raise SystemExit("Missing board socket art asset")
    socket_text = board_socket.read_text(encoding="utf-8")
    if "<svg" not in socket_text or "<title" not in socket_text or "Occult altar tile socket" not in socket_text:
        raise SystemExit("Board socket art asset lacks expected SVG/title markup")
    for asset in ALTAR_TILE_ASSETS:
        path = ROOT / asset
        if asset.endswith(".svg"):
            text = path.read_text(encoding="utf-8")
            if "<svg" not in text or "<title" not in text:
                raise SystemExit(f"Tile asset lacks SVG/title markup: {asset}")
            continue
        expected_size = 48 if "/48/" in asset else 96
        width, height = png_dimensions(path)
        if (width, height) != (expected_size, expected_size):
            raise SystemExit(f"Tile asset has wrong dimensions: {asset} is {width}x{height}")


verify_source_hooks()
assert_single_shape("horizontal line", [(1, 1), (2, 1), (3, 1)], "line")
assert_single_shape("vertical line", [(4, 1), (4, 2), (4, 3)], "line")
assert_single_shape("four line relic", [(2, 3), (3, 3), (4, 3), (5, 3)], "line")
assert_single_shape("five line seed rune", [(1, 3), (2, 3), (3, 3), (4, 3), (5, 3)], "line")
assert_single_shape("l shape", [(2, 2), (3, 2), (4, 2), (2, 3), (2, 4)], "l")
assert_single_shape("t shape", [(2, 3), (3, 3), (4, 3), (3, 4), (3, 5)], "t")
assert_single_shape("cross shape", [(3, 3), (2, 3), (4, 3), (3, 2), (3, 4)], "cross")
assert_no_match("diagonal-only cluster", [(2, 2), (3, 3), (4, 4)])

print("HTML match-shape regression checks passed.")
